### ISSUE TITLE
VPN Auto switching

### ISSUE THREAD

**Issue by pro7777777777** [farshadz1997/Microsoft-Rewards-bot#102]
Hi is was wondering if you could add a vpn auto switcher to change the ip address every five accounts

**Comment by farshadz1997** [comment]
Hi, no I can't do that, due to each user's account belongs to specific location, there's no way to add VPN that supports all locations. Plus that, many free vpns are not safe to use them for Microsoft Rewards.

**Comment by pro7777777777** [comment]
Oh ok np
