### ISSUE TITLE
Earned points calculation is incorrect, always 100

### ISSUE THREAD

**Issue by pilonull** [farshadz1997/Microsoft-Rewards-bot#105]
Hello, love the bot. I think beginning in a recent update the earned points calculation has been having issues. 

![image](https://user-images.githubusercontent.com/8344590/219418853-bce532d4-4ddc-4cca-876e-70585dfdc05c.png)

As you can see between the two days, it says it only farmed 100 points each day.. but in reality it farmed 480 points on each of the accounts. Not a HUGE deal, but figured I'd drop ya a line about it. 

It seems it's occurring in both the discord notifications and in the console log output. 
![image](https://user-images.githubusercontent.com/8344590/219419507-45e64d78-2e22-4396-91dc-95a4176305e3.png)

Looks like it started on/around february 10th, I think when I updated to the latest version.

**Comment by farshadz1997** [comment]
Hello,
I think you have encountered an error at start of mobile section, occurrence of an error caused to restart the point counter.

**Comment by pilonull** [comment]
> Hello, I think you have encountered an error at start of mobile section, occurrence of an error caused to restart the point counter.

Ah yea, I just noticed all this in the app log: 
![image](https://user-images.githubusercontent.com/8344590/219481600-a571a43c-8923-48bb-b85b-262fcada3776.png)

How would I go about fixing it?

**Comment by farshadz1997** [comment]
It doesn't have any clue about the source of problem. :(

**Comment by pilonull** [comment]
Resolved it by deleting the folder and "reinstalling" it

**Comment by farshadz1997** [comment]
fixed points counter for log 1f63f14
