### ISSUE TITLE
Misdate in telegram message

### ISSUE THREAD

**Issue by KevinNitroG** [farshadz1997/Microsoft-Rewards-bot#115]
It is 19/2/2023 now but the calendar icon in telegram message is still on 17 🙄🙄
![IMG_20230219_113546](https://user-images.githubusercontent.com/86353526/219958163-32f3c46e-742b-4f4d-9599-ba1bd8992786.jpg)

**Comment by farshadz1997** [comment]
That calender is just static Icon
