### ISSUE TITLE
is not working.

### ISSUE THREAD

**Issue by LearnerSir** [farshadz1997/Microsoft-Rewards-bot#119]
After downloading file from github i extracted it ran pip install requirement it said to it could be updated to further I didn't do anything but downloaded chromium driver and pasted in same directory and after editing json file i ran python file and it closed so fast I couldn't see even what was error i am lil bit extra noob if you could help me a little be i would be extremely grateful drop in dm at discord @Learner-vai#7384 Thank You.

**Comment by farshadz1997** [comment]
Open cmd in farmer directory, type '''python ms_rewards_farmer.py''' your problem might related to webdriver or accounts file

**Comment by LearnerSir** [comment]
> you have to paste chromedriver in windows folder as shown in readme page
> 
> which extension file is chromedriver?

**Comment by farshadz1997** [comment]
> > you have to paste chromedriver in windows folder as shown in readme page
> > which extension file is chromedriver?

chromedriver.exe

**Comment by kimjinzhan** [comment]
> you have to paste chromedriver in windows folder as shown in readme page

That's a brillant idea! THX!

**Comment by Prabh-Saini** [comment]
looks like its resolved considering the issue has been stagnate for >1 month, and automatic chromedriver has been added in #186. @farshadz1997
