### ISSUE TITLE
Argument --session 

### ISSUE THREAD

**Issue by Bajuware1337** [farshadz1997/Microsoft-Rewards-bot#12]
Hello, 
what does the argument "--session" mean?
I tried it, but nothing different happened than before.
It's not a problem, just the information would interest me.
TY

**Comment by farshadz1997** [comment]
Hi,
It creates a "Profiles" in your bot directory for your accounts and save all cookies there and use them whenever you use session again, in this case it doesn't need to login to your account by user and password, Microsoft reads the session and cookies then sign in you automatically.

**Comment by Bajuware1337** [comment]
Sounds good thanks

**Comment by farshadz1997** [comment]
Hi, it shouldn't happen unless your region changed by your IP or anything that goes wrong with your account
