### ISSUE TITLE
Total Points not Updating...

### ISSUE THREAD

**Issue by jnelson89** [farshadz1997/Microsoft-Rewards-bot#120]
In logs while sending to telegram the total points of account is not updating and its only sending to telegram before farmed points but not after farmed updated points!! Fix this ASAP, please...

**Comment by farshadz1997** [comment]
I checked it, looks everything fine, are you sure?

**Comment by Rickyose** [comment]
> I checked it, looks everything fine, are you sure?

hi i just wonder if you already read my comment here, that might slip in because its old thread https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/97 ?? wonder if you can fix the issue? thank you

**Comment by jnelson89** [comment]
> I checked it, looks everything fine, are you sure?

Sometimes when bot stucks in bing login loop or timeout loop its happening...

**Comment by jnelson89** [comment]
Now with latest commit points not even logging in txt i think the code to save logs in global var LOGS is missing in farmer function, check once...

**Comment by farshadz1997** [comment]
> Now with latest commit points not even logging in txt i think the code to save logs in global var LOGS is missing in farmer function, check once...

fixed it
