### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by xDriss** [farshadz1997/Microsoft-Rewards-bot#121]
Hi can you in he next update add proxy for each account option in This version like GUI V2

**Comment by farshadz1997** [comment]
Added in, just add a field named ```proxy``` for the accounts you want in ```accounts.json```. proxy must be without authentication.

**Comment by farshadz1997** [comment]
Added in, just add a field named ```proxy``` for the accounts you want in ```accounts.json```. proxy must be without authentication.

**Comment by Rickyose** [comment]
> Added in, just add a field named `proxy` for the accounts you want in `accounts.json`. proxy must be without authentication.

Hi i am bit confused here, how can i use proxy ?? can you check mine if there is something wrong there?

[
    {
        "username": "xxx@outlook.com",
        "password": "xxx",
	   "proxy": "123.456.78.90:58117"
    }
]

Thats my accounts.json, is that correct ?? because my account still not use my proxy using that config, my proxy is also using socks5 instead http

**Comment by farshadz1997** [comment]
You added in correct format, but I just tested http proxy. I'll check socks5
