### ISSUE TITLE
Check if ms_farmer is updated

### ISSUE THREAD

**Issue by inverspe** [farshadz1997/Microsoft-Rewards-bot#127]
you should add a text warning indicating "Outdated Version" just before the app starts farming
check the repo for latest version?

**Comment by farshadz1997** [comment]
It's on my plan to add it.

**Comment by Prabh-Saini** [comment]
duplicate #127

**Comment by Prabh-Saini** [comment]
sure they do track a lot of information but theres no other convenient solution atm.
