### ISSUE TITLE
Traceback proxy error UnboundLocalError: local variable 'browser'

### ISSUE THREAD

**Issue by emazack** [farshadz1997/Microsoft-Rewards-bot#129]
hi :)
I've got this error:

`  File "....\ms_rewards_farmer.py", line 1559, in farmer
    browser = browserSetup(False, PC_USER_AGENT, account.get('proxy', None))
  File "....t\ms_rewards_farmer.py", line 83, in browserSetup
    if ARGS.use_proxy and proxy is not None:
AttributeError: 'Namespace' object has no attribute 'use_proxy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "....\ms_rewards_farmer.py", line 1688, in <module>
    main()
  File "....t\ms_rewards_farmer.py", line 1672, in main
    farmer()
  File "....\ms_rewards_farmer.py", line 1632, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment`

the version compatibility between the Chrome browser and ChromeDriver is fine

**Comment by emazack** [comment]
ok <3

**Comment by emazack** [comment]
I dont know if you solved the problem but it is still not working, just pulled new changes @farshadz1997 the error is more or less the same

**Comment by farshadz1997** [comment]
```AttributeError: 'Namespace' object has no attribute 'use_proxy'``` do you still have this in error?

**Comment by emazack** [comment]
Traceback (most recent call last):
  File "......\ms_rewards_farmer.py", line 1589, in farmer
    browser = browserSetup(True, account.get('mobile_user_agent', MOBILE_USER_AGENT, account.get('proxy', None)))
TypeError: get expected at most 2 arguments, got 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".....\ms_rewards_farmer.py", line 1689, in <module>
    main()
  File ".....\ms_rewards_farmer.py", line 1673, in main
    farmer()
  File "....\ms_rewards_farmer.py", line 1633, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
PS C:\Users\emzac\Documents\Rewards\Microsoft-Rewards-bot>

**Comment by farshadz1997** [comment]
@emazack Sorry for this kind of bugs. try this, it must solve it.
[ms_rewards_farmer.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/10844323/ms_rewards_farmer.zip)
