### ISSUE TITLE
 tasks not all done

### ISSUE THREAD

**Issue by Bajuware1337** [farshadz1997/Microsoft-Rewards-bot#13]
Hello, since a few days I have the problem that the bot doesn't do all the tasks. Unfortunately, upgrading to the latest Chrome driver didn't help.

**Comment by xCorteX** [comment]
I've also had the problem for the last few days, then tried several browsers to see if it was the settings, but none of the browsers opened a pop-up for the tasks...

Then I changed the IP and everything worked again.

could it be that a fixed ip address was blacklisted?

**Comment by farshadz1997** [comment]
Hello, could you please tell me which task hasn't done by bot?

> could it be that a fixed ip address was blacklisted?

I have no clue about it

**Comment by Bajuware1337** [comment]
![Daily](https://user-images.githubusercontent.com/106429230/173412205-e78dd7c5-9fcd-4875-ba0a-b4db0636ac4a.JPG)

for me, for example, it's the bonus quiz and reward survey in the daily tasks today

**Comment by Bajuware1337** [comment]
![not done](https://user-images.githubusercontent.com/106429230/173412459-6d402c5f-97bd-4d96-ba07-fbdb37548135.JPG)

to me it looks like the problem is with tasks with pupup

**Comment by Bajuware1337** [comment]
https://gist.github.com/Bajuware1337/ec370afe674af3a63243d673356740ec

**Comment by farshadz1997** [comment]
Sorry for delay,
I launched the script over your data and I think found the problem, Accept cookie popup and Bing wallpaper app ad blocked the quiz, please tell me if you also have these popups

![Screenshot 2022-06-18 180359](https://user-images.githubusercontent.com/60227955/174458590-969e55da-6854-45de-b563-ee82f8702cc6.png)

![Screenshot 2022-06-18 180445](https://user-images.githubusercontent.com/60227955/174458586-891ff3b8-224a-4f3c-9965-e32787c7be6e.png)

**Comment by Bajuware1337** [comment]
no problem.  Yes, I have these popups too

**Comment by Bajuware1337** [comment]
I Tired is. if i close the popup the tasks are done, if i don't close it, it aborts.  can you disable these popups somehow or treat them in the script?

**Comment by farshadz1997** [comment]
I solved it but I need to do few more tests and do some refactoring, I'll upload it till tomorrow.

**Comment by kobi-wan** [comment]
I tested the new version of the script, but it does not do the daily quiz (Kaffeepause). And there were no blocking popups.
But it does one other daily and some other missing punchcards.

**Comment by kobi-wan** [comment]
What I see is, that the script doesn't even try to solve the quiz, it doesn't recognize it.

Here is the link from today's quiz, which also wasn't resolved: [https://www.bing.com/search?q=Physik&rnoreward=1&mkt=DE-DE&FORM=ML12JG&skipopalnative=true&rqpiodemo=1&filters=BTEPOKey:%22REWARDSQUIZ_DEDE_ThursdayBonus_20220623%22%20BTROID:%22Gamification_DailySet_DEDE_20220623_Child2%22%20BTROEC:%220%22%20BTROMC:%2230%22](url)

But I have to solve it sometime today in order to keep my daily streak. :)

**Comment by kobi-wan** [comment]
![Daily](https://user-images.githubusercontent.com/28985724/175518438-c1ebb484-f6e6-480b-9d9a-48a81f8b0535.png)
![More Cards](https://user-images.githubusercontent.com/28985724/175518460-0ebf0661-b1a6-44c0-b677-add71f6b29f6.png)

Random cards :(

**Comment by Bajuware1337** [comment]
![Aufgaben1](https://user-images.githubusercontent.com/106429230/175771283-5467ee90-aacb-464f-93e3-293575ae918a.JPG)
![Aufgaben 2](https://user-images.githubusercontent.com/106429230/175771287-ce17502e-aa25-4f50-acc5-d106947e0b2d.JPG)

[ Link ](https://gist.github.com/Bajuware1337/2c232f22021655f7c525baac4c1522e7)
This is my status today after completing the tasks.

**Comment by farshadz1997** [comment]
I tested your data; everything looks normal but first card of your daily, somehow it flagged as completed from Microsoft and bot couldn't detect it. **Ziel festlegen** and **Mehr punkte** in more activity are unpredictable and they're not defined in bot, for **URL rewards** promotions such as **Afrikanische Schonheiten**, sometimes it takes more time to submit, and it may come from Microsoft or network issues.
Remember that if any error rises in daily tasks, punch cards and more activities, it leaves the whole section and continues to next task.
I attached your dashboard data in case that if you would like to check it.

[dashboard.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/8985613/dashboard.zip)

**Comment by farshadz1997** [comment]
It seems that many people have issue with quests as they post it on [Microsoft Rewards Reddit](https://www.reddit.com/r/MicrosoftRewards/comments/vkioyc/the_daily_set_click_it_doesnt_work_very_well/).

**Comment by kobi-wan** [comment]
Everything seems working normal so far now, except for surveys.

![Survey](https://user-images.githubusercontent.com/28985724/177733084-1a5bf95b-3229-4311-8c5b-76269abe9138.png)

**Comment by Culetto** [comment]
> Everything seems working normal so far now, except for surveys.
> 
> ![Survey](https://user-images.githubusercontent.com/28985724/177733084-1a5bf95b-3229-4311-8c5b-76269abe9138.png)

Yeah same problem for me, it seems like a microsoft issue though not sure if it's the bot fault

**Comment by Culetto** [comment]
> It seems to relate to the workaround for the bing wallpaper app popup.
> 
> So if you comment out the 3 lines from line [498 ](https://github.com/farshadz1997/Microsoft-Rewards-bot/blob/master/ms_rewards_farmer.py#L498-L500) on in **completeDailySetSurvey** function, it works for me.
> 
> EDIT: You also have to comment out the Accept cookie popup workaround in that same function from line [494 ](https://github.com/farshadz1997/Microsoft-Rewards-bot/blob/master/ms_rewards_farmer.py#L494-L496) on. Only if both are deactivated, it's working for me.

I tested this and it works thanks for the fix bro

**Comment by farshadz1997** [comment]
I don't know how it makes problem for you because if there's no popups it will never go into the if clause to try bypass the popups.

**Comment by kobi-wan** [comment]
> I don't know how it makes problem for you because if there's no popups it will never go into the if clause to try bypass the popups.

I tried to investigate what happens.
The survey is opened normal at first. Then, after the `browser.switch_to.window(window_name = browser.window_handles[1])` in line 491, the first browser tab with the rewards page is focused for a short moment and then it is closed.
Then the rewards page is loaded in the that same tab and the script continues with the other tasks.

But the script never gets past the ` if isElementExists(..` line. It seems that these lines cause that strange behaviour.

**Comment by farshadz1997** [comment]
> > I don't know how it makes problem for you because if there's no popups it will never go into the if clause to try bypass the popups.
> 
> I tried to investigate what happens.
> The survey is opened normal at first. Then, after the `browser.switch_to.window(window_name = browser.window_handles[1])` in line 491, the first browser tab with the rewards page is focused for a short moment and then it is closed.
> Then the rewards page is loaded in the that same tab and the script continues with the other tasks.
> 
> But the script never gets past the ` if isElementExists(..` line. It seems that these lines cause that strange behaviour. 

I found it, iselementexists function does not called right in survey function so it raises an error and causes reset_tabs function to be called. I'll fix it in my next commit.
Thanks for your help.
