### ISSUE TITLE
[REQUEST] - Addition of an superfast Mode

### ISSUE THREAD

**Issue by EliteDev2** [farshadz1997/Microsoft-Rewards-bot#130]
hey,
With the --fast mode its still kind of slow with all those sleep timers even after adjusting some myself.
It would be great if you can add an even --Faster mode for people with good internet speed.

**Comment by TatsP** [comment]
Did you manage to make it faster? Let's connect on Discord?

**Comment by abhistark999** [comment]
i have only reduced some sleep timer so its only a lil bit faster but not much.
drop your discord username if u like to talk

**Comment by farshadz1997** [comment]
The only thing I can do is to reduce or remove sleeps, there's nothing I can do other than this.

**Comment by EliteDev2** [comment]
It will be great if you can reduce some timers such that it  wont cause much issues.

Or if you can add an feature to run multiple accounts at once simultaneously...
**For example:**  Passing `--limit 3` argument will allow the bot to farm 3 account at the same time

**Comment by farshadz1997** [comment]
someone was working on parallel farming, he said he will create merge request once is ready.

**Comment by TatsP** [comment]
> someone was working on parallel farming, he said he will create merge request once is ready.

Could you show me which sleep timers to adjust to make it faster? I think the promotions and quizzes can be made faster but I am not able to do so as editing the timers breaks the bot somehow.

**Comment by inverspe** [comment]
theres no point in adding that when you can just use headless mode

**Comment by Grietis748** [comment]
Yeah,its so slow even with fast mode.

**Comment by Prabh-Saini** [comment]
I will add `--superfast` to the code. It will take me a day or two (considering its 9pm here lol). I am clueless on how parallel farming would even work though.

**Comment by Prabh-Saini** [comment]
once #152 is added this github issue can be closed

**Comment by Prabh-Saini** [comment]
@farshadz1997 You can close this issue.
