### ISSUE TITLE
Proxy support per account 

### ISSUE THREAD

**Issue by JittoJoseph** [farshadz1997/Microsoft-Rewards-bot#135]
Could you maybe add a way to use custom proxy per account?
Instead of just one single proxy for all accounts.
If you can maybe put a proxy options with the username and password options in the accounts.json

**Comment by farshadz1997** [comment]
It is there, use it exactly as you said. I just forgot to add it in readme.
```
{
    "username": "user",
    "password": "pwd",
    "proxy": "your http proxy"
}
```
