### ISSUE TITLE
Bonus quiz isn't recognized

### ISSUE THREAD

**Issue by kobi-wan** [farshadz1997/Microsoft-Rewards-bot#141]
The bonus quiz of the daily set isn't recognized by the bot.

![Screenshot 2023-03-09 105727](https://user-images.githubusercontent.com/28985724/223986832-b98285cc-3696-4c4e-82d9-8f9a081d1447.jpg)

I tried to run the script several times also on different computers but without success. I can send you source code of the page if you want.

**Comment by farshadz1997** [comment]
it works well on US accounts, source code might help.

**Comment by kobi-wan** [comment]
I've sent it to you by email.

**Comment by kobi-wan** [comment]
Again, the bot can't solve one of the daily sets (tried running it several times).

![Screenshot 2023-03-20 100309](https://user-images.githubusercontent.com/28985724/226293714-18101174-704f-4a58-a2fe-075fea0a1240.jpg)

**Comment by Prabh-Saini** [comment]
Hey @kobi-wan, the issue I see is that you started it and then stopped the bot halfway through (accidently or intentionally). The bot cannot recognize partial completion, and will assume that it has been completed and will skip it. You will notice that it will fully complete a quiz/this or that if it has not been started yet. Implementing completing partial completions would take a lot of time and effort for something which is easily avoidable, and therefore i think @farshadz1997 should close this issue.

**Comment by kobi-wan** [comment]
Okay, I didn't know that the bot can't handle partial completed quizzes. So I agree, that I have to solve it on my own. No problem there.
My main concern is, that I don't want to loose my daily streak. If one of these above things happen (partial completed or not), I will not be informed about it and then I loose the streak (which already happened). That's my problem.

**Comment by farshadz1997** [comment]
@kobi-wan I checked your dashboard, and it was good.
As @Prabh-Saini on said, on daily set bot can't complete partial completion, on the other hand it can complete partial completion quizzes on more activities.

**Comment by kobi-wan** [comment]
> @kobi-wan I checked your dashboard, and it was good. 

Yeah, because I had to complete it, in order not to loose my daily streak.

You already had a function built into the script, so that it was informing the user, if the daily streak wasn't increased. See [here](https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/32).  But it's not in the script any more. :(
