### ISSUE TITLE
Is there a way to keep a log of the run?

### ISSUE THREAD

**Issue by sanzo-mlgb** [farshadz1997/Microsoft-Rewards-bot#143]
I'm not talking about `Logs_accounts.txt`.

When the program is running, you can see the LOGO of this project and what actions are currently being performed. I want to save this information.

I tried `python ms_rewards_farmer.py --fast --session --autoexit > 123123`, but there is no output on the screen, and there is nothing inside the 123123 file either, even though I can see that the program is running normally

I want to keep a log of the run, is there a way to do this? 

thank you

**Comment by farshadz1997** [comment]
I don't know, one approach is to I replace all prints with logger module.
