### ISSUE TITLE
how do i get it to add my email

### ISSUE THREAD

**Issue by jakubadkinnnnn** [farshadz1997/Microsoft-Rewards-bot#144]

**Comment by farshadz1997** [comment]
What do you mean?

**Comment by jakubadkinnnnn** [comment]
when i go on the jason sample i put my credentials but then what do i do. how do i save the changes?

**Comment by farshadz1997** [comment]
first, remove ```.sample``` from file, then add your credentials and then save the file with text editor or press ```ctrl+s``` to save it

**Comment by jakubadkinnnnn** [comment]
i did it but when i run it it still says your email not my email

**Comment by farshadz1997** [comment]
There must be another file named accounts.json, enter your infos in that file

**Comment by jakubadkinnnnn** [comment]
when i save it what type of file should i save it as

**Comment by farshadz1997** [comment]
it is already ```.json```, don't change it.

**Comment by farshadz1997** [comment]
have you deleted the first account in accounts.json?

**Comment by jakubadkinnnnn** [comment]
no

**Comment by farshadz1997** [comment]
remove it, it was just a sample, that's why you get your email

**Comment by jakubadkinnnnn** [comment]
how

**Comment by farshadz1997** [comment]
replace "your email" and "your password" with your credentials.
