### ISSUE TITLE
Can I run this script in WSL2 without any visible UI?

### ISSUE THREAD

**Issue by Untacki** [farshadz1997/Microsoft-Rewards-bot#158]
Actually,I run into the same question as "local variable 'browser' referenced before assignment" when i run this script in WSL2.
![image](https://user-images.githubusercontent.com/38031755/225616079-f3d6f0ed-e0aa-4461-b4bf-6906152d5ba1.png)
I had checked the chrome version and chromedriver version,I'm sure that they are same.
So this script have to run in the visible browser unless in the headless mode?

**Comment by farshadz1997** [comment]
edge also support headless but using edge can cause some errors.

**Comment by Prabh-Saini** [comment]
i feel like the solution to this is just use chrome headless, and probably just disable edge headless stating it being unreliable.

**Comment by farshadz1997** [comment]
Edge user agent has been set in bot so you get Edge points. you don't need to use Edge webdriver for those points.

**Comment by Untacki** [comment]
> Edge user agent has been set in bot so you get Edge points. you don't need to use Edge webdriver for those points.

Okay,thanks
