### ISSUE TITLE
Failed to complete MSN Shopping Game 

### ISSUE THREAD

**Issue by Prabh-Saini** [farshadz1997/Microsoft-Rewards-bot#159]
**Region:** `Australia`
**Terminal:** `[MSN GAME] Failed to complete MSN shopping game !`
**--error:** Nothing

**More:** It definitely does exist because I saw the game and then the script just closed the tab saying failed to complete msn shopping game.

I know this information really doesn't help at all, I'll see if I can get more information like xpath and whatever tomorrow, because its sorta late today.

**Comment by Albertjokers** [comment]
> how often does bot fails on MSN quiz?

It fails every time for me. I don't know if it relates to my location since I am from Canada but, I cannot complete it. And, also. 

The mobile agent support doesn't work. I check and see after the farmer is done and it hasn't used it. 

Also, can you add pc user agent? The software doesn't use that either. I don't know how to add it.

**Comment by Prabh-Saini** [comment]
i think mine sometimes plays a few of them and then closes the tab and says it failed. however my mobile useragent does work so idk about that.

**Comment by farshadz1997** [comment]
> It fails every time for me. I don't know if it relates to my location since I am from Canada but, I cannot complete it. And, also. 
> 
> The mobile agent support doesn't work. I check and see after the farmer is done and it hasn't used it. 
> 
> Also, can you add pc user agent? The software doesn't use that either. I don't know how to add it. 

How do you know that your mobile user agent not working?
PC's user agent are same most of time, change it globally in script.

**Comment by farshadz1997** [comment]
> i think mine sometimes plays a few of them and then closes the tab and says it failed. however my mobile useragent does work so idk about that. 

If sometimes it works for you then the code works fine but there's unexpected error in yours, I guess you can modify the code and find it because it works flawlessly on US accounts that i tested multiple times.

**Comment by Prabh-Saini** [comment]
Just for the record all of mine failed today. I will look through the code to see if i can figure something out but that will take some time

**Comment by farshadz1997** [comment]
Thanks for your help, I'm sorry that I can't help you with this as I don't have any AU account.

**Comment by Prabh-Saini** [comment]
Mate, thank you for your help. I am clueless to how on Earth a lot of those functions even work at all.

**Comment by Prabh-Saini** [comment]
@farshadz1997, @Albertjokers what is your screen size, resolution, and percentage of zoom, and also in msn shopping can you see all the cards without having to click the arrow? 

I ask this because I believe the issue from testing (not really testing, it's just me reading an error) is that it fails because of ElementClickInterceptedException. Which would be caused by the option being behind the arrow and therefore also would reason why it sometimes succeeds yet sometimes fails. This could easily be resolved using a javascript solution referenced in #175

**Comment by Albertjokers** [comment]
> @farshadz1997, @Albertjokers what is your screen size, resolution, and percentage of zoom, and also in msn shopping can you see all the cards without having to click the arrow? 
> 
> 
> 
> I ask this because I believe the issue from testing (not really testing, it's just me reading an error) is that it fails because of ElementClickInterceptedException. Which would be caused by the option being behind the arrow and therefore also would reason why it sometimes succeeds yet sometimes fails. This could easily be resolved using a javascript solution referenced in #175 

It's defo not that. I think I may have found the fix for my issue. I tested it out.

For some reason. The MSN shopping game doesn't work on a Canadian ip for some reason. But when I change to a US Ip it completes it successfully.

I think that is why it doesn't work.

**Comment by Prabh-Saini** [comment]
MSN shopping game does not relate to your ip, the actual issue is that selenium fails to click the submit button because the click is somehow intercepted by the home page?? And for some reason sometimes its successful and sometimes it's not. @farshadz1997, any ideas or solutions?

**Comment by farshadz1997** [comment]
you were going to change zoom of your browser, didn't help? or change the windows zoom, most of the time on small FHD screens windows set zoom to 125%

**Comment by Prabh-Saini** [comment]
So at first I changed it to 75% because I thought it would've fixed it. However, I then changed it to 125% today, and found that it works flawlessly (based off of it running 6 times).

**Comment by farshadz1997** [comment]
Glad you could fix it, on my 15.6 Inch Laptop with 1902×1080 resolution and zoom 100% works without problem
