### ISSUE TITLE
No module Named ipapi

### ISSUE THREAD

**Issue by lilxanny** [farshadz1997/Microsoft-Rewards-bot#16]
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 7, in <module>
    import ipapi
ModuleNotFoundError: No module named 'ipapi'

**Comment by ESHARK22** [comment]
Install requirements with the following command :
pip install -r requirements.txt

(Read the instructions. They are there for a reason :-] )

**Comment by lilxanny** [comment]
> Try to install requirements with the following command : pip install -r requirements.txt
> 
> (Read the instructions. They are there for a reason :-] )

I have already done that, i even tried installing ipapi separately, ireinstalled python, i tried replacing ipapi by Ipyrthon.core.ipapi,and nothing seems to work.

**Comment by lilxanny** [comment]
Requirement already satisfied: ipapi in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (1.0.4)
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from ipapi) (2.26.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from requests->ipapi) (2020.4.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from requests->ipapi) (2.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from requests->ipapi) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from requests->ipapi) (1.26.10)

**Comment by ESHARK22** [comment]
Can you please send the output of this command (which lists the version(s) of python installed):
py -0

**Comment by lilxanny** [comment]
Installed Pythons found by py Launcher for Windows
 -3.9-64 *
 -3.8-64
 -3.7-64

**Comment by farshadz1997** [comment]
That's not good, maybe your interpreter is looking for the package in wrong python path, try using virtual environment it may fix your problem.

**Comment by lilxanny** [comment]
How do i do that?

**Comment by farshadz1997** [comment]
You can learn it in this [article](https://medium.com/pythoneers/how-to-create-a-virtual-environment-in-python-9c243ed3a54c#:~:text=Creating%20Python%20virtual%20environment%20%28Windows%20version%29%201%20To,a%20directory%20for%20Environments.%20...%20More%20items...%20).

**Comment by lilxanny** [comment]
Traceback (most recent call last):
  File "MicrosoftRewardsBot.py", line 1238, in <module>
    main()
  File "MicrosoftRewardsBot.py", line 1206, in main
    LoadAccounts()
  File "MicrosoftRewardsBot.py", line 1088, in LoadAccounts
    ACCOUNTS = json.load(open("accounts.json", "r"))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 7 column 1 (char 99)

**Comment by lilxanny** [comment]
okay i will try it on a virtual environement

**Comment by lilxanny** [comment]
This virtual environement is kind of long, so i'll try it later,however, can you see whether i can fix this new error?I fixed the module error by using pip3.9 instead of pip, but now it gives me this error which is probably related to a problem reading json file.
Traceback (most recent call last):
File "MicrosoftRewardsBot.py", line 1238, in
main()
File "MicrosoftRewardsBot.py", line 1206, in main
LoadAccounts()
File "MicrosoftRewardsBot.py", line 1088, in LoadAccounts
ACCOUNTS = json.load(open("accounts.json", "r"))
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json_init_.py", line 296, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json_init_.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 340, in decode
raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 7 column 1 (char 99)

**Comment by ESHARK22** [comment]
You could try to specify which version of python of python to use. e.g:
py -3.9 -m pip install ipapi
py -3.9 MicrosoftRewardsBot.py
