### ISSUE TITLE
Repeat MSN shopping argument

### ISSUE THREAD

**Issue by inverspe** [farshadz1997/Microsoft-Rewards-bot#160]
Add an optional argument that would attempt to play **MSN Shopping** over and over again until it completes.

It fails to play or find the game sometimes—not too often, but it's good to have this to prevent it from missing any days without completing the **MSN game**.

**Comment by farshadz1997** [comment]
this will make the farmer slower.

**Comment by inverspe** [comment]
> this will make the farmer slower.

Yes, but it's optional and not ON by default.

**Comment by Prabh-Saini** [comment]
Hey @inverspe, try changing your zoom to 125% and re-running the script. Let me know if it works or if it has issues (make sure to use `--error` and paste the error log if so). 

If no response is received, this issue will be marked as stagnate, and closed.

**Comment by Prabh-Saini** [comment]
Thank you @inverspe for your contribution, I have implemented your solution in to the code. The issue will be closed shortly.
