### ISSUE TITLE
Cant get past "

### ISSUE THREAD

**Issue by Permissiblekillos** [farshadz1997/Microsoft-Rewards-bot#162]

**Comment by Permissiblekillos** [comment]
never gets past ensuring login on bing (it is)
just refreshes the page forever

**Comment by farshadz1997** [comment]
Set your Bing in English if it is not, then look at the Rewards icon at top of the page, if it doesn't display your points there then look for the problem, as long as bot couldn't locate your points it won't pass ensuring login.

**Comment by Permissiblekillos** [comment]
It shows points + English + when I click on it says it is logged in

**Comment by Permissiblekillos** [comment]
python ms_rewards_farmer.py --session --fast btw

**Comment by farshadz1997** [comment]
can you send a screenshot of Bing and send the source code of the page if it's possible for you.

**Comment by Permissiblekillos** [comment]
![image](https://user-images.githubusercontent.com/92329464/226140302-78c61144-e2b8-43f9-bec3-7bde8d406488.png)
  and idk what u mean by the sourcecode of the page

**Comment by Permissiblekillos** [comment]
![image](https://user-images.githubusercontent.com/92329464/226140389-7633b43a-c82f-4191-be44-170044a0d297.png)

**Comment by Permissiblekillos** [comment]
![image](https://user-images.githubusercontent.com/92329464/226140571-3fbfeb26-9d91-438c-b4a5-b6901c9bc415.png)

**Comment by farshadz1997** [comment]
Your page looks good.

> and idk what u mean by the sourcecode of the page

right click on page, click on save as, when you choosing the location of save, change save as type to "Webpage, single file". send the file for me.

**Comment by Permissiblekillos** [comment]
https://cdn.discordapp.com/attachments/1001591911775211540/1086816930943471737/Bing.mhtml

uploaded on discord cuz it said unsupported file type^

**Comment by Permissiblekillos** [comment]
The problem seems to have fixed it self. Don't know why/how cuz never changed anything nor restarted pc, coulda been something weird on the website idk

**Comment by Permissiblekillos** [comment]
stopped working 💀
