### ISSUE TITLE
Help us protect your account prompt

### ISSUE THREAD

**Issue by AG4lyf** [farshadz1997/Microsoft-Rewards-bot#163]
this prompt cause the script to loop 
![image](https://user-images.githubusercontent.com/45149585/226218489-d095601d-b7b6-4fae-9b4a-0bda9753156d.png)

i will attach the html alongside url in next message to skip this prompt.

**Comment by AG4lyf** [comment]
![image](https://user-images.githubusercontent.com/45149585/226219184-316914a6-256a-4dff-9fe2-e181dc175b30.png)
console looks something like this. 
PS. this is not an actual console but a discord chat that i myself modified the script to send logs to.

**Comment by AG4lyf** [comment]
[message.txt](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/11012665/message.txt)
https://account.live.com/proofs/Add?mkt=EN-US&uiflavor=web&client_id=xxxxxxxx&cobrandid=xxxxxx&id=00000&mpcxt=CATB&sn=502411&ru=https://login.live.com/oauth20_authorize.srf%3fuaid%3d7cf4f98edaed45598ee646be2817b09d%26cobrandid%3d03c8bbb5-2dff-4721-8261-a4ccff24c81a%26client_id%3dxxxxxxxxx0f%26opid%3d5A46234FECD213AA%26mkt%3dEN-US%26opidt%3d1679271413

**Comment by AG4lyf** [comment]
sometimes it return back from `[LOGIN] Ensuring login on Bing...` instead of logged-in successfully message

**Comment by AG4lyf** [comment]
```
def RewardsLogin(browser: WebDriver):
    #Login into Rewards
    browser.get(BASE_URL)
    if str(browser.current_url).startswith("https://account.live.com/proofs/Add"):
        browser.find_element(By.ID, 'iShowSkip').click()
        browser.get(BASE_URL)
```

fixes the issue.

**Comment by Prabh-Saini** [comment]
No point in that, because if you go to the top image it quite clearly states "Skip for now (5 days until this is required)". Unless you add a warning in both terminal and discord (in the webhook which gives the daily result), this fix doesn't really help.

**Comment by AG4lyf** [comment]
adding a temporary fix is better than not adding anything at all and make the script look forever without doing anything.

i guess adding a warning is really needed. in that case you can take out the text from the button and just relay it to console and discord/telegram.

**Comment by Prabh-Saini** [comment]
okay your right. adding this seems really easy to be honest at the top we set up a global variable and everytime it detects "proofs/add" in the url we can add `message_proof += f"{email} requires proof to be added as soon as possible\n"` and in messages just put in `message_proof`.

**Comment by farshadz1997** [comment]
@AG4lyf get the latest version and use ```--skip-unusual``` arg to skip unusual activity. tell me if you it works

**Comment by farshadz1997** [comment]
@AG4lyf get the latest version and use ```--skip-unusual``` arg to skip unusual activity. tell me if you it works

**Comment by AG4lyf** [comment]
with the recent update
requirements.txt doesn't have "tkinter" mentioned @Prabh-Saini

**Comment by AG4lyf** [comment]
plus the "€" sign on https://github.com/farshadz1997/Microsoft-Rewards-bot/blob/master/ms_rewards_farmer.py#L1686 is not a standard and causes the script to not run at tall on linux
![image](https://user-images.githubusercontent.com/45149585/226765691-4df479ad-5586-4f6f-8446-964cff3e2f0e.png)

are you guys just checking script on windows ?

**Comment by AG4lyf** [comment]
and it took me a hefty 40 minutes finding it.

**Comment by Prabh-Saini** [comment]
Didn't know, I'll add it into readme.md

**Comment by AG4lyf** [comment]
@Prabh-Saini why is the whole check is inside a "if ARGS.session" block ? 
this make it non useful if you don't use session/

**Comment by farshadz1997** [comment]
> @Prabh-Saini why is the whole check is inside a "if ARGS.session" block ? this make it non useful if you don't use session/

There's one check for session and there's one for those who are not using sessions.
