### ISSUE TITLE
Are there any free reliable apps available to verify phone numbers for Microsoft Rewards

### ISSUE THREAD

**Issue by Albertjokers** [farshadz1997/Microsoft-Rewards-bot#164]
Are there any free reliable apps available to verify phone numbers for Microsoft Rewards

Can anyone recommend a reliable app to verify phone numbers for Microsoft Rewards? I've been using the bot for a while now and would like to ensure that my phone number is properly verified. Thanks in advance for any suggestions!

**Comment by petrosaurus8** [comment]
Try this https://www.textverified.com

**Comment by Albertjokers** [comment]
> Try this https://www.textverified.com

Are there free alternatives? Maybe apps I guess?

**Comment by Prabh-Saini** [comment]
use parents, family, and friends phone numbers if possible

**Comment by Albertjokers** [comment]
> use parents, family, and friends phone numbers if possible

Yeah.. I can use maybe 1. But that's it. If there isn't any other option what should I use to verify the number

**Comment by petrosaurus8** [comment]
It's gonna be hard to find free, you can try https://www.textnow.com/ also there is some apps that offer free numbers, search it on google play

**Comment by Prabh-Saini** [comment]
Considering there really isn't one, I think we do need to unfortunately close this issue. @farshadz1997
