### ISSUE TITLE
The bot doesn't complete the quizes. Placed image below to show what is happening..

### ISSUE THREAD

**Issue by Albertjokers** [farshadz1997/Microsoft-Rewards-bot#165]
The bot doesn't seem to collect the rewards challenges and tours. I've placed an image down below to show that the bot is skipping the quizzes.

Surprisingly, the bot does this with every account I farmed it with. 

Does this happen with anybody else? Or is it just me?

Is there any fix?
![Screenshot 2023-03-20 000803](https://user-images.githubusercontent.com/128176514/226245219-7aa28617-33d5-4706-9a84-99cc32e2e532.png)

**Comment by Prabh-Saini** [comment]
hey its something odd with microsoft surveys, all the other surveys work fine, right?

**Comment by Albertjokers** [comment]
> hey its something odd with microsoft surveys, all the other surveys work fine, right? 

Yup, it's just those. but everything else works fine.

**Comment by farshadz1997** [comment]
Microsoft surveys and take tour not supported.
