### ISSUE TITLE
«Bug» Closing chrome after loading the page of rewards

### ISSUE THREAD

**Issue by Conirefle** [farshadz1997/Microsoft-Rewards-bot#17]
Chrome colsing and reoping as the py retry endlessly to put email on the rewards site.

**Comment by Conirefle** [comment]
[LOGS] Logs loaded successfully.

********************icrylol@gmail.com********************

DevTools listening on ws://127.0.0.1:58707/devtools/browser/47c8a106-e6af-46b4-972e-bef5f2968263
[LOGIN] Logging-in...
[LOGIN] Writing email...


********************icrylol@gmail.com********************

DevTools listening on ws://127.0.0.1:58729/devtools/browser/30f2cd21-40e0-40e1-8223-2c3b49ec6790
[LOGIN] Logging-in...
[LOGIN] Writing email...

**Comment by farshadz1997** [comment]
I think you are using Selenium 4, if it is, try downgrade to Selenium 3.141.0, it's because the functions that been used in bot are no longer support in Selenium 4. 
I'm going to update functions as well.

**Comment by farshadz1997** [comment]
I updated functions, update your bot and try again

**Comment by Conirefle** [comment]
@farshadz1997 Okay now it works flawlessly, does it support multi user?

**Comment by farshadz1997** [comment]
Yes it does, add your accounts in **accounts.json** as I explained in readme.
