### ISSUE TITLE
Make MSN shopping optional

### ISSUE THREAD

**Issue by GioPresta** [farshadz1997/Microsoft-Rewards-bot#176]
Since msn shopping is sadly not available in all parts of the world, could it become optional?
Activated by a code such as increased speed
So as to save time, since the activity is done but no points are earned

I thank you in advance

**Comment by Prabh-Saini** [comment]
@farshadz1997 `--skipshopping` and `--skipfitness`

**Comment by Prabh-Saini** [comment]
yeah i can add a feature like that, within a few days
