### ISSUE TITLE
Automatic unlock and redeem with otp number

### ISSUE THREAD

**Issue by GioPresta** [farshadz1997/Microsoft-Rewards-bot#177]
An interesting feature would be automatic unlocking in case of blocking by using numbers taken at https://sms-activate.org/
There are api on the site
It could also be used for automatic redeem

**Comment by Prabh-Saini** [comment]
its a paid service, and these numbers might already be used which might get you banned. The idea is not bad, however it is just unrealistic for this to be added. Also I believe these are VoIP numbers so i'm not sure if it will work anyway.

**Comment by GioPresta** [comment]
> its a paid service, and these numbers might already be used which might get you banned. The idea is not bad, however it is just unrealistic for this to be added. Also I believe these are VoIP numbers so i'm not sure if it will work anyway.

no they are not VoIp and yes they are paid but little stuff, obviously you need to have a balance on the site and the numbers have always been reliable, I have been using them for some time and no bans
