### ISSUE TITLE
#Suggestion A DISCORD!!!! 

### ISSUE THREAD

**Issue by Neksha** [farshadz1997/Microsoft-Rewards-bot#180]
u should make a discord :))
so people can talk about this like
tom60 chats rewards farmer!
i can help make it and boost it.

**Comment by farshadz1997** [comment]
your help would be much appreciated. I really don't have time to create and manage a server

**Comment by niklasbaranski** [comment]
You could also run a bot on the Discord server that runs the Microsoft bot itself. If you need any help, feel free to contact me! I appreciate your work.

**Comment by Axel3026** [comment]
@niklasbaranski farm from the discord itself? wtf

**Comment by niklasbaranski** [comment]
> @niklasbaranski farm from the discord itself? wtf

Discord bot, yes.

**Comment by Neksha** [comment]
of course i shall start making the discord right away! :))

**Comment by Axel3026** [comment]
> > @niklasbaranski farm from the discord itself? wtf
> 
> Discord bot, yes.

Wow, help me. Axel3026#6927

**Comment by Neksha** [comment]
https://discord.gg/qFd97RjAvz beta version! join up

**Comment by Prabh-Saini** [comment]
can we close this considering there is a server now and its in readme.md? @farshadz1997
