### ISSUE TITLE
New box prevents script from running

### ISSUE THREAD

**Issue by kobi-wan** [farshadz1997/Microsoft-Rewards-bot#19]
Hi there,
a new box with terms of use appeared today. You have to confirm it, in order to sign in.
![TermsOfUse](https://user-images.githubusercontent.com/28985724/185587872-1ff92bb1-f5f5-4375-b911-140bb991948d.jpg)
So the script tries and tries and never gets past the login process. I clicked it manually and then it continues without further problems.

**Comment by HQModz** [comment]
Having the same issue, bot no longer works

**Comment by farshadz1997** [comment]
please upload HTML source of the page in Github gist and tell me after what page it comes

**Comment by kobi-wan** [comment]
Does not work with `--session` argument. It shows the new box and then the script quits with an unknown error message.

Without the session argument, it is working fine.

**Comment by farshadz1997** [comment]
I'm working on it.
