### ISSUE TITLE
Terms & Conditions changes make for failed login (UNKNOWN ERROR)

### ISSUE THREAD

**Issue by dothatdomain1** [farshadz1997/Microsoft-Rewards-bot#20]
The script is really good - a big improvement on the original.

Microsoft have changed their terms & conditions and this leads to a pop-up after the login window which causes the script to fail due to an unknown error.

Is there anyway to update the script so that it can click 'Next' in order to proceed as usual?

Thanks in advance.

**Comment by farshadz1997** [comment]
I'm working on it, since I already accept new terms on my account it's a bit difficult for me to test changes on script.

**Comment by dothatdomain1** [comment]
That’s great news, thanks for the help!

If you need a spare MS account to try it with, let me know - i'm more than happy to make one for you.

**Comment by farshadz1997** [comment]
Thanks for your generous offer, I'm going to create a one for testing.

**Comment by farshadz1997** [comment]
Please update your bot and test it, then tell me the result.
Thanks

**Comment by dothatdomain1** [comment]
I've just updated & have had running for about an hour - I believe it's going well as I'm yet to encounter any terms & conditions pop ups yet! Thanks for your very fast help with this, it's really appreciated.

Another unrelated question (in the form of an enhancement) - is it possible to make the bot go a bit faster? I have 1gbps internet and so it would be good to be able to make the use of it. I understand that some internet connections may not warrant a faster version.

I think right now the bot is taking about 30 mins or over to complete per account, which is in reality much slower than it would take the average human (on good connection) to complete - I think it should probably take anywhere from 5 to 15 minutes per account to complete. If it's adjustable by speed that would be great.

Thanks in advance again for your kind help.

**Comment by dothatdomain1** [comment]
UPDATE: I have just witnessed it and can confirm that the update works as intended.

**Comment by farshadz1997** [comment]
Glad to see your problem fixed.

> I think right now the bot is taking about 30 mins or over to complete per account, which is slower than it would take the average human (on good connection) to complete - I think it should probably take anywhere from 5 to 15 minutes per account to complete. If it's adjustable by speed that would be great.

I'll try to make an option for making it faster within next few days.
