### ISSUE TITLE
accounts loops instead of timeout

### ISSUE THREAD

**Issue by AG4lyf** [farshadz1997/Microsoft-Rewards-bot#202]
there are particular points in the script. 
in those points. if it fails to validate login. the accounts loops instead of timing out.

**Comment by AG4lyf** [comment]
ps. #163 is one of the case. 
it haven't been fixed. i just checked.

**Comment by Prabh-Saini** [comment]
hasn't been fixed in one of the recent commits? @farshadz1997 developed the fix for #163

**Comment by farshadz1997** [comment]
I developed the fix but couldn't test it as it requires to have an account to get unusual activity, I created the fix with HTML file provided

**Comment by AG4lyf** [comment]
let me try to get an account you can test it.
I will probably DM you if i get my hands on one.

**Comment by farshadz1997** [comment]
@AG4lyf could you please try this? I added some fixes for the issue, tell me if it works then I'll push it to master.
[ms_rewards_farmer.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/11147073/ms_rewards_farmer.zip)

**Comment by AG4lyf** [comment]
I think the last piece to this puzzle was the "Help us secure your account" prompt which was discussed [here](https://discord.com/channels/1088311257360253010/1088311258522066965/1104950724703567883) . I think we can now close this issue.
