### ISSUE TITLE
what if i want to use multipal country 

### ISSUE THREAD

**Issue by whitestorm007** [farshadz1997/Microsoft-Rewards-bot#204]
microsoft rewards support two country at a time to grind ,

**Comment by rayjay8** [comment]
Just delete the log file and start again

**Comment by Prabh-Saini** [comment]
> microsoft rewards support two country at a time to grind ,

this will likely get you banned, but yes deleting logs will work. @farshadz1997 you can close this

**Comment by whitestorm007** [comment]
yup , sorry i forgot to check mail 😅
