### ISSUE TITLE
Shopping game do not work with --headless mode

### ISSUE THREAD

**Issue by tommaso-ascani** [farshadz1997/Microsoft-Rewards-bot#206]
When bot runs with --headless mode do not work shopping game, but if i try without --headless mode it works, someone have the same problem? and someone fix it?

Logs:
```
[MSN GAME] Trying to complete MSN shopping game...
[MSN GAME] Checking if user is signed in ...
[MSN GAME] Answering questions ...
Message: element click intercepted: Element is not clickable at point (778, 361)
  (Session info: chrome=111.0.5563.146)
Stacktrace:
#0 0xaaaad056e99c <unknown>
#1 0xaaaad0359880 <unknown>
#2 0xaaaad03949c0 <unknown>
#3 0xaaaad0392f40 <unknown>
#4 0xaaaad03911b4 <unknown>
#5 0xaaaad03905b0 <unknown>
#6 0xaaaad0386178 <unknown>
#7 0xaaaad0385af8 <unknown>
#8 0xaaaad03c2f68 <unknown>
#9 0xaaaad0384350 <unknown>
#10 0xaaaad0385328 <unknown>
#11 0xaaaad05b9a54 <unknown>
#12 0xaaaad05bc6a8 <unknown>
#13 0xaaaad05bccf0 <unknown>
#14 0xaaaad05a5334 <unknown>
#15 0xaaaad05bd40c <unknown>
#16 0xaaaad0597854 <unknown>
#17 0xaaaad05dc368 <unknown>
#18 0xaaaad05dc4f0 <unknown>
#19 0xaaaad05f521c <unknown>
#20 0xffffa4505624 <unknown>
#21 0xffffa403a49c <unknown>

[MSN GAME] Failed to complete MSN shopping game !
```

**Comment by Prabh-Saini** [comment]
does it work normally? do you use different zooms? what os? speed (eg. normal, fast, superfast)?

**Comment by Prabh-Saini** [comment]
are you using session, if so is it the same session. one possible issue may be zoom. if you are using session please change the browser zoom level to 125% in `chrome://settings`.

**Comment by V1NAY007** [comment]
Ok so it has again stopped working while in headless, works without it now.

**Comment by tommaso-ascani** [comment]
I found that if you add browser.set_window_size(1920, 1080) it works for me on ubuntu (avoid not interactable error) but i cant resolve others errors on raspberrypi (dietpi os), i will find the problem
