### ISSUE TITLE
Ask about running update.py on Ubuntu

### ISSUE THREAD

**Issue by KevinNitroG** [farshadz1997/Microsoft-Rewards-bot#207]
Is that update.py doesn't work on Ubuntu sir?
When I run update command and run the script. This is the log
![image](https://user-images.githubusercontent.com/86353526/229575306-4d6e51eb-d962-40c7-88a9-072bcaf5e719.png)
When I try running on github workspace. Seem that it cannot move file from temp to main dir
![image](https://user-images.githubusercontent.com/86353526/229575577-eb420fe6-f84d-4515-841d-8f2ab18d730b.png)
Am I wrong somewhere 🫢🤔😅

**Comment by Prabh-Saini** [comment]
hm it seems like your thing is saying that that it tried to move the file temp/readme.md to temp/readme.md which obviously failed because well you can't move a file to where it already is. i'm not sure why this is happening, i'll look into it.

**Comment by KevinNitroG** [comment]
^^ I will wait for your latest code

**Comment by Prabh-Saini** [comment]
I've been able to replicate your exact issue using Github Codespaces, I will come up with a solution soon

**Comment by KevinNitroG** [comment]
> Fixed in #210. Thanks for your bug report, greatly appreciated!

Thank you for fixing the bug ♥️🥰

**Comment by Prabh-Saini** [comment]
thank you, you motivated me to fix a lot of the github issues here lol
