### ISSUE TITLE
addition of --virtualdisplay flag. 

### ISSUE THREAD

**Issue by AG4lyf** [farshadz1997/Microsoft-Rewards-bot#208]
In current state the "createDisplay" function is locked behind headless mode
headless is still a risky thing to do. 
i say we create a flag that uses the virtualdisplay regardless of headless mode or not.

**Comment by Prabh-Saini** [comment]
Thank you @AG4lyf for your contribution. The idea you have suggested has been implemented inside the code.

**Comment by AG4lyf** [comment]
![image](https://user-images.githubusercontent.com/45149585/232108857-f881f660-2bd7-43fb-8065-19fc8a3d61e8.png)
doesn;t work. and stop closing issues if they haven't been confirmed fixed ? @Prabh-Saini @farshadz1997

**Comment by AG4lyf** [comment]
![image](https://user-images.githubusercontent.com/45149585/232110304-e42b7dd5-c5e2-436a-8f2b-70f8bd57d23f.png)
this should also take care that a virtual display is being used.

**Comment by AG4lyf** [comment]
let me add a pull request for this.
