### ISSUE TITLE
New option for --repeatvpn workflow

### ISSUE THREAD

**Issue by CodeREViewee** [farshadz1997/Microsoft-Rewards-bot#214]
Session retained for multi points vpn farming.

Process flow:

1. Account1 login (browser / mobile)
2, validate login
3. farm account1
4. prompt user to repeat step 2 (change vpn) or end (start next account)

Is there a way i can farm while retaining the session or maybe it could be a coded option?.  My accounts are getting locked when i try to relogin on a different location via vpn.  Im doing this manually for months now and i happend at see your work here, wondering if this could be included.

**Comment by CodeREViewee** [comment]
My manual process includes:

1. login account1
2. farm account1
3. change vpn
4. farm account1
5. change vpn
6. farm account1
7. change vpn
8. login account2
9. farm account2
10. change vpn
11. farm account2
12. and so on

**Comment by farshadz1997** [comment]
It's not possible to add this for this repo, because in that case all users have to use soecific VPN, however you could read the API doc of your VPN and implement this in script.

**Comment by CodeREViewee** [comment]
I tried using the --account option, not sure if im thinking its the same option that i needed, but everytime I use it, it just open a browser then close, then a prompt saying Press enter to close once your finished.  I though this would run the farmer using the specific account session and bypass the login process.  Im using this command line, or do i need to add more?

python .\ms_rewards_farmer.py  --account-browser someuser@hotmail.com --session

**Comment by farshadz1997** [comment]
no, --account-browser do something else.

**Comment by CodeREViewee** [comment]
> it opens the session belongs to the account if you have used --session before on that account.

I did launch initially farm with --session after it was completed, I tried loading --account-browser it just load the browser then exit and it states that Press enter to exit once im done? is that the normal outcome? was expecting it to load the last session for that account with the browser still on.

**Comment by farshadz1997** [comment]
I'll check it

**Comment by Prabh-Saini** [comment]
> ount-browser it just load the browser then exit and it states that Press enter to exit once im done? is that the normal outcome? was expecting it to load the last session for that account with the browser still on.

whats the difference between just using --session everytime and using --account_browser?

**Comment by farshadz1997** [comment]
when you use --session bot will use it for farming, --account-browser opens the session that has been created before for user to do manual works on the account such redeem or unblock the account etc

**Comment by CodeREViewee** [comment]
> 

if this is fixed, can you still do the farm but dont need to login and just use the existing session based on the --account_browser?

**Comment by farshadz1997** [comment]
I fixed the browser closing immediately. before that you could use the session to for that

**Comment by CodeREViewee** [comment]
is it possible to have --account-browser-farm same but has the option to farm with the exisiting session?

**Comment by CodeREViewee** [comment]
> I fixed the browser closing immediately. before that you could use the session to for that

confirmed working thanks
