### ISSUE TITLE
fails to complete daily set

### ISSUE THREAD

**Issue by aydynx** [farshadz1997/Microsoft-Rewards-bot#22]
logs that its trying to complete, but then closes and tries to login to the first account

**Comment by aydynx** [comment]
i have just found this only happens on new accounts, and they need to click through the join Microsoft rewards dialogs.

**Comment by aydynx** [comment]
seems like it doesnt claim the initial 100 bonus points either..

**Comment by aydynx** [comment]
https://gist.github.com/aydynx/7cebe82345b83fc20ad19708b1960f0f

**Comment by farshadz1997** [comment]
I found the problem, I'll fix it in few days
