### ISSUE TITLE
Cannot get past the welcome page

### ISSUE THREAD

**Issue by yukiryo** [farshadz1997/Microsoft-Rewards-bot#220]
![image](https://user-images.githubusercontent.com/58250223/230018852-786c999c-66ef-4813-8db3-d529d7e65d95.png)
![image](https://user-images.githubusercontent.com/58250223/230018865-2f1adcd9-3ec0-4b44-b834-d41c71437651.png)
Cannot get past the welcome page, no response after clicking

**Comment by Prabh-Saini** [comment]
I've never seen that homepage, it might just be a Japanese thing. But what is stopping you from just simply clicking the X on the top right?

**Comment by yukiryo** [comment]
> I've never seen that homepage, it might just be a Japanese thing. But what is stopping you from just simply clicking the X on the top right?

Every time I open rewards it comes up and causes a failure

**Comment by farshadz1997** [comment]
try do it manually and then run it on bot.

**Comment by Prabh-Saini** [comment]
Well unfortunately, if this issue is unreproducible for anyone, it's likely that we won't be able to help you. Your best chance is completing all the activities it asks because at the moment it says 0/50, if you make that 50/50, it might not come back?

**Comment by yukiryo** [comment]
I thought so too, but unfortunately, after I selected the selections, it wouldn't move on to the next step, it got stopped there

**Comment by juanplayerofc** [comment]
> I thought so too, but unfortunately, after I selected the selections, it wouldn't move on to the next step, it got stopped there

Do you use VPN? it happens to me when i already farmed 2 countries

**Comment by yukiryo** [comment]
> Do you use VPN? it happens to me when i already farmed 2 countries

yes, this won't happen in US, but elsewhere

**Comment by mevichi15** [comment]
This PR could solve it https://github.com/farshadz1997/Microsoft-Rewards-bot/pull/267
