### ISSUE TITLE
MSN Game failed

### ISSUE THREAD

**Issue by yukiryo** [farshadz1997/Microsoft-Rewards-bot#221]
[MSN GAME] Trying to complete MSN shopping game...
[MSN GAME] Checking if user is signed in ...
[MSN GAME] Answering questions ...
Message: element click intercepted: Element <div style="--i:2" class="shopping-game-card-outline  shopping-game-selected-card">...</div> is not clickable at point (1121, 803). Other element would receive the click: <shopping-modal config-instance-src="default" instance-id="ShoppingModal" data-t="{&quot;n&quot;:&quot;ShoppingModal&quot;,&quot;t&quot;:8}" selectedofferidinmodalnav="72584162902" topcarouselloadtimeskey="1680684205751_72584162902_TopCarousel"></shopping-modal>
  (Session info: chrome=112.0.5615.50)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x01165E23+53059]
        (No symbol) [0x010F4AF1]
        (No symbol) [0x00FEB388]
        (No symbol) [0x010241D8]
        (No symbol) [0x01021CA4]
        (No symbol) [0x0101F3AB]
        (No symbol) [0x0101DC58]
        (No symbol) [0x01012DE7]
        (No symbol) [0x0103A7CC]
        (No symbol) [0x01012746]
        (No symbol) [0x0103AB24]
        (No symbol) [0x0105066F]
        (No symbol) [0x0103A5C6]
        (No symbol) [0x01010A2C]
        (No symbol) [0x010120ED]
        GetHandleVerifier [0x013CD3CE+2573550]
        GetHandleVerifier [0x01403340+2794592]
        GetHandleVerifier [0x013FCF1C+2768956]
        GetHandleVerifier [0x011FFA60+682880]
        (No symbol) [0x010FEE22]
        (No symbol) [0x010FA8B8]
        (No symbol) [0x010FA99B]
        (No symbol) [0x010EDB57]
        BaseThreadInitThunk [0x75F97D49+25]
        RtlInitializeExceptionChain [0x774FB74B+107]
        RtlClearBits [0x774FB6CF+191]

[MSN GAME] Failed to complete MSN shopping game !

**Comment by farshadz1997** [comment]
There's an issue about this already so I close this.
