### ISSUE TITLE
is it possible to make it so that when you claim a code (for example amazon) it will send the code in the discord webhook?

### ISSUE THREAD

**Issue by MeekTortoise** [farshadz1997/Microsoft-Rewards-bot#222]

**Comment by yannikbaranski** [comment]
I believe it is, and I suppose @farshadz1997 will add such a feature soon.

**Comment by Prabh-Saini** [comment]
That would be super awesome! However, I'm not sure if the method to redeem is uniform across all regions. In Australia, there's these 8 characters "security code" e.g. "A1B2-C3D4" and you go to this site which I can't remember on the top of my head, but there you enter the code, and it will then show you the Amazon gift card code. At the moment your best bet is probably setting up all your Microsoft accounts from one Gmail email (using the dot trick). For example:
Main email: johnappleseed@gmail.com
Account 1:  johnappleseed@gmail.com
Account 2:  john.appleseed@gmail.com
Account 3:  johnapple.seed@gmail.com
Account 4:  j.ohnappleseed@gmail.com
and etc...

**Comment by MeekTortoise** [comment]
In my country (the netherlands) you don't have enter any code, just go to the transaction page and click a button

**Comment by farshadz1997** [comment]
the variety of getting gift codes are to much, some of them required to go to another website to get them and some you can get them directly from order history, and it different among regions and gift cards.

**Comment by MeekTortoise** [comment]
ok, thanks

**Comment by DraussenSho** [comment]
dot trick work with registration?

**Comment by MeekTortoise** [comment]
yes

**Comment by Prabh-Saini** [comment]
Close as unplanned? @farshadz1997

**Comment by farshadz1997** [comment]
> Close as unplanned? @farshadz1997 

Yes
