### ISSUE TITLE
Ipapi Issue 

### ISSUE THREAD

**Issue by pro7777777777** [farshadz1997/Microsoft-Rewards-bot#225]
The program was working perfectly and then this happened 

Traceback (most recent call last):
  File "/Users/myname/Downloads/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 15, in <module>
    import ipapi
ModuleNotFoundError: No module named 'ipapi'

**Comment by yannikbaranski** [comment]
You can manually install it by using the following command:
`pip install ipapi`

**Comment by pro7777777777** [comment]
I am still getting the same error

**Comment by pro7777777777** [comment]
I fixed it It turned out I had two versions of Python installed
