### ISSUE TITLE
when i type wt in the file explorer chrome says "this website cant be reached"

### ISSUE THREAD

**Issue by salbbbbbbbert** [farshadz1997/Microsoft-Rewards-bot#228]
![unfinished (1)](https://user-images.githubusercontent.com/120865284/230495622-e1e0afb7-b1ee-4eaa-b4fe-cec9591b83e0.png)
![wt](https://user-images.githubusercontent.com/120865284/230495623-aaca0eb1-5e8b-4ef1-b00b-6a582f984c82.PNG)

**Comment by Prabh-Saini** [comment]
That's quite the inconvenience, try this [tutorial](https://www.lifewire.com/open-command-prompt-in-a-folder-5185505).
