### ISSUE TITLE
Hey I can't update code if there is .github folder

### ISSUE THREAD

**Issue by KevinNitroG** [farshadz1997/Microsoft-Rewards-bot#231]
As you can see I couldn't update my code because it was `unable to downloading .github(Status: 404)`
![image](https://user-images.githubusercontent.com/86353526/230609896-9af9a256-3cbd-4554-8047-02346d1e15f9.png)

**Comment by farshadz1997** [comment]
get new ```update.py``` file, I added ```.github``` folder in ignore files. 1b506d4

**Comment by KevinNitroG** [comment]
Nice 😊

**Comment by farshadz1997** [comment]
no it doesn't

**Comment by KevinNitroG** [comment]
> no it doesn't

Okayy thank you

**Comment by farshadz1997** [comment]
get new update file, fixed it now
