### ISSUE TITLE
auto update not working

### ISSUE THREAD

**Issue by Conirefle** [farshadz1997/Microsoft-Rewards-bot#233]
![image](https://user-images.githubusercontent.com/34823518/230640256-79c093c2-1b2b-489e-86ce-aa3952592410.png)
Can't auto update, linux.

**Comment by farshadz1997** [comment]
Your python is < 3.10

**Comment by pro7777777777** [comment]
I am getting the error

[UPDATER] Unable to downloading .github (Status: 404)

**Comment by farshadz1997** [comment]
Get new updater
