### ISSUE TITLE
Run Everyday is not working

### ISSUE THREAD

**Issue by pilonull** [farshadz1997/Microsoft-Rewards-bot#24]
Hello

Long time fan of this script, but I've always had this issue... today it's bothered me enough to create this issue..

I typically start the script using `python3.9 ms_rewards_farmer.py --everyday 12:00`
and it works great the first time the script is run.. however, the next day, it just hangs on "Logs loaded successfully" and does not execute the script.. If I leave it running for another day, it just adds another line of "Logs loaded successfully"

I'm not sure how to fix it...

![image](https://user-images.githubusercontent.com/8344590/187461686-f815d067-e2ba-4b04-ba2e-89077ba6d4bb.png)

I've also found another post, https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/6#issuecomment-1122093881
that I'd ideally like to use with something like crontab or systemd, however, I've edited the script but cannot get it to run successfully like that comment states. Not sure if the code has changed or what I need to do to get it to work. 

Any help or guidance is appreciated.

**Comment by dothatdomain1** [comment]
I had the same problem, but have you tried setting it to 23:59 instead? That worked for me.

**Comment by pilonull** [comment]
> I had the same problem, but have you tried setting it to 23:59 instead? That worked for me.

Have not tried that, but sounds promising, as maybe since the script starts one day, then finishes the next day, it'll be good to go for the next day.. 

Still gonna hold my breath to see if I can run it as a service instead of always having it open, but this sounds like it could definitely be a viable workaround..

Thanks!

**Comment by farshadz1997** [comment]
Hi
I think I found the problem, after my test I'll update it. thanks for letting me know

**Comment by farshadz1997** [comment]
@pilonull please update your bot, I think you won't have problem anymore. update me with result

**Comment by pilonull** [comment]
> @pilonull please update your bot, I think you won't have problem anymore. update me with result

updated the bot, gonna take me until tomorrow to be able to tell if it's fixed or not but I will update you as soon as I find out

**Comment by pilonull** [comment]
> @pilonull please update your bot, I think you won't have problem anymore. update me with result

Looks like it's fixed, thanks very much!
