### ISSUE TITLE
Ask for using your repo to create public repo running on GA

### ISSUE THREAD

**Issue by KevinNitroG** [farshadz1997/Microsoft-Rewards-bot#244]
Hi. I'm currently using your bot on GA _(Github Action)_ and I want to share my repo to other people if they want to try. Of course they will try on their own responsibility. My repo doesn't store your code in the main repo. It will download the your bot only when running GA, and after that it will commit `Log_accounts.txt` into the repo. We can modify the yml file to change the use. _(But I'm not really good at coding so perhaps my code is quite messy)_
Could you please read my code and allow me to continue sharing my Repo? I respect your decision because you are the owner of the bot. If you agree, I will make a README.md for it and hope you suggest me more in the code. 
Here is [my repo link on WaybackMachine](https://web.archive.org/web/20230411055929/https://github.com/KevinNitroG/MSRB-GA) _(I have deleted my repo because I need your agreement first)_
Thank you for reading this, and hope you have a good day.

**Comment by Prabh-Saini** [comment]
i dont think farshadz can do this because he could get the repo taken down for abusing github actions

**Comment by KevinNitroG** [comment]
> i dont think farshadz can do this because he could get the repo taken down for abusing github actions

Huhm I do think so
I will wait for his answer. If he decline then I will make it private.

**Comment by JittoJoseph** [comment]
This is pretty good

**Comment by Not-Dhanraj** [comment]
> i dont think farshadz can do this because he could get the repo taken down for abusing github actions

I agree. This will surely get github attention for abusing Github actions. I'm pretty sure that i saw another repo taken down cause people were forking it and running it on github actions. That repo got around 50 stars and like 20-30 forks in a week. Few days later, repo got nuked.
We don't want that. Do we?

**Comment by farshadz1997** [comment]
@KevinNitroG as others said it's against their TOS, if you want to teach others create a readme and send it to Discord.

**Comment by KevinNitroG** [comment]
> @KevinNitroG as others said it's against their TOS, if you want to teach others create a readme and send it to Discord.

Kay I got it

**Comment by JittoJoseph** [comment]
@KevinNitroG you on discord?, Can I get your Id?

**Comment by KevinNitroG** [comment]
> @KevinNitroG you on discord?, Can I get your Id?

I don't use discord regularly. Here is my [message](https://discord.com/channels/1088311257360253010/1088311258303971449/1095353881241845770) on Farshadz1997 Discord server  
If you want to chat with me, use [telegram](https://gist.github.com/KevinNitroG/t.me/KevinNitro) instead
