### ISSUE TITLE
Error when running ms_farmer

### ISSUE THREAD

**Issue by Dr0mus** [farshadz1997/Microsoft-Rewards-bot#247]
So you know how you run the main script and it checks if there's an update and it spits out a window that tells you to update. I am running my script on a headless pi and it gives me the error: `no display name and no $DISPLAY environment variable`. It kind of gets annoying when you run it using --start-at sometime and it spouts an error because its headless and . Can you add a option like `--auto-update` so it doesn't open a gui menu when checking for updates or something similar.

**Comment by Prabh-Saini** [comment]
—dont-check-for-updates exists, also are you running headless, because you say your taspberry pi is running headless. if your rpi doesnt have a screen, chromium cant magically pop up you will have to use —headless

**Comment by Dr0mus** [comment]
Oh thank you, didn't know that was a command. I forgot to mention I am using `--virtual-display` as well.
