### ISSUE TITLE
A feature to ignore logs / add VPN option

### ISSUE THREAD

**Issue by PttsDev** [farshadz1997/Microsoft-Rewards-bot#252]
With a VPN you can claim points twice a day, but the bot won't run since the daily run has been already performed. 
It would be nice to have an option like ``--vpn`` or ``--ignore-logs`` that allows the bot to rerun without reading the logs (i don't know if it already exists but at least I haven't found anything)

**Comment by farshadz1997** [comment]
VPN is not going to be implemented. you could just delete logs and run again.

**Comment by PttsDev** [comment]
Oh I didn't know it lead to bans since I'm new to this and saw people doing that. Thanks for the warning, it makes sense actually that earning more points will eventually get you banned.
I'll close the issue then!
