### ISSUE TITLE
Browser error

### ISSUE THREAD

**Issue by Gnaagounet** [farshadz1997/Microsoft-Rewards-bot#253]
### Environnment: 
Python: 3.10.6
OS: Ubuntu 22.04.2 LTS
pip 23.0.1 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)

### pip list
Package                Version
---------------------- -------------
async-generator        1.10
attrs                  21.2.0
Automat                20.2.0
Babel                  2.8.0
bcrypt                 3.2.0
blinker                1.4
certifi                2022.12.7
chardet                4.0.0
charset-normalizer     3.0.1
click                  8.0.3
cloud-init             23.1.1
colorama               0.4.4
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
cryptography           3.4.8
dbus-python            1.2.18
distro                 1.7.0
distro-info            1.1build1
exception              0.1.0
exceptiongroup         1.1.0
func-timeout           4.3.5
h11                    0.14.0
httplib2               0.20.2
hyperlink              21.0.0
idna                   3.3
importlib-metadata     4.6.4
incremental            21.3.0
ipapi                  1.0.4
jeepney                0.7.1
Jinja2                 3.0.3
jsonpatch              1.32
jsonpointer            2.0
jsonschema             4.17.3
keyring                23.5.0
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
lxml                   4.9.2
MarkupSafe             2.0.1
more-itertools         8.10.0
netifaces              0.11.0
nose                   1.3.7
notifiers              1.3.3
oauthlib               3.2.0
outcome                1.2.0
packaging              23.0
pexpect                4.8.0
Pillow                 9.5.0
pip                    23.0.1
pip-review             1.3.0
ptyprocess             0.7.0
pyasn1                 0.4.8
pyasn1-modules         0.2.1
PyGObject              3.42.1
PyHamcrest             2.0.2
PyJWT                  2.3.0
pyOpenSSL              21.0.0
pyotp                  2.8.0
pyparsing              2.4.7
pyrsistent             0.18.1
pyserial               3.5
PySocks                1.7.1
python-apt             2.4.0+ubuntu1
python-debian          0.1.43ubuntu1
python-docx            0.8.11
python-dotenv          1.0.0
python-magic           0.4.24
pytz                   2022.1
PyVirtualDisplay       3.0
PyYAML                 5.4.1
Random-Word            1.0.7
requests               2.28.2
SecretStorage          3.3.1
selenium               4.4.3
service-identity       18.1.0
setuptools             59.6.0
six                    1.16.0
sniffio                1.3.0
sortedcontainers       2.4.0
sos                    4.4
ssh-import-id          5.11
systemd-python         234
tqdm                   4.65.0
trio                   0.22.0
trio-websocket         0.9.2
Twisted                22.1.0
ubuntu-advantage-tools 8001
ubuntu-drivers-common  0.0.0
ufw                    0.36.1
unattended-upgrades    0.1
urllib3                1.26.5
wadllib                1.3.6
webdriver-manager      3.8.5
wheel                  0.37.1
wsproto                1.2.0
xkit                   0.0.0
xvfbwrapper            0.2.9
zipp                   1.0.0
zope.interface         5.4.0

### Command:  
python3 /home/***/Microsoft-Rewards-bot-master/ms_rewards_farmer.py --headless --fast --telegram xxx xxx

### Prompt with error:

    ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
            by @Charlesbel upgraded by @Farshadz1997        version c7d070e

[FLAGS] headless: True
[FLAGS] fast: True
[FLAGS] telegram: ['xxx', 'xxx']
[UPDATER] Your version (c7d070e) is up to date!

[LOGS] "Logs_accounts.txt" file not found.
[LOGS] "Logs_accounts.txt" created.

********************aaa@aaa********************
[WDM] - Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.75M/6.75M [00:00<00:00, 34.7MB/s]

Traceback (most recent call last):
  File "/home/xxx/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2530, in farmer
    browser = browserSetup(
  File "/home/xxx/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 136, in browserSetup
    browser = webdriver.Chrome(options=options) if ARGS.no_webdriver_manager else webdriver.Chrome(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x55d50ad66fe3 <unknown>
#1 0x55d50aaa5d36 <unknown>
#2 0x55d50aad2459 <unknown>
#3 0x55d50aace051 <unknown>
#4 0x55d50aacaa9b <unknown>
#5 0x55d50ab0caf7 <unknown>
#6 0x55d50ab0c11f <unknown>
#7 0x55d50ab03693 <unknown>
#8 0x55d50aad603a <unknown>
#9 0x55d50aad717e <unknown>
#10 0x55d50ad28dbd <unknown>
#11 0x55d50ad2cc6c <unknown>
#12 0x55d50ad364b0 <unknown>
#13 0x55d50ad2dd63 <unknown>
#14 0x55d50ad00c35 <unknown>
#15 0x55d50ad51138 <unknown>
#16 0x55d50ad512c7 <unknown>
#17 0x55d50ad5f093 <unknown>
#18 0x7f72128e0b43 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2829, in <module>
    main()
  File "/home/xxx/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2784, in main
    farmer()
  File "/home/xxx/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2723, in farmer
    if browser is not None:
UnboundLocalError: local variable 'browser' referenced before assignment
local variable 'browser' referenced before assignment

### TODO: 
Do you know how to solve this error ?

**Comment by Gnaagounet** [comment]
No idea ? I'm stuck with this version :(

**Comment by farshadz1997** [comment]
Hi

Have you tried --no-webdriver-manager?

**Comment by Gnaagounet** [comment]
It works, thanks :)
