### ISSUE TITLE
How to setup Totp

### ISSUE THREAD

**Issue by desis123** [farshadz1997/Microsoft-Rewards-bot#259]
First of all thanks for this awesome project. Can anyone please explain how to use / setup  totp  . I am kind of confused how it will work, Any suggestion will be greatly appreciated. Thanks again for the whole thing .

**Comment by pro7777777777** [comment]
It is a Time-based One-time Password (I think)

**Comment by Prabh-Saini** [comment]
im pretty sure you sign up for ms authenticator and from there you get the otp string which you use in the bot
