### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Sellu112** [farshadz1997/Microsoft-Rewards-bot#261]
![Screenshot_20230414-140225__01__01](https://user-images.githubusercontent.com/130745166/231990335-434ae5b3-2f55-41cb-a928-db5d749cc4d2.jpg)

It was fine before..idk what happened rn
Please can someone give me a fix?
I did install chromium-chromedriver and used no chromedriver arg in terminal, it still shows this error.
I'm currently using Ubuntu 22.04 and Andronix (it was fine till yesterday, I reinstalled ubuntu and this happened).
@farshadz1997 @Prabh-Saini

**Comment by farshadz1997** [comment]
Another person is experiencing the same issue; try rolling back to Chrome 111.

**Comment by Prabh-Saini** [comment]
Why did you manually download chromedriver when the bot automatically installs it for you? @Sellu112

**Comment by Sellu112** [comment]
> Another person is experiencing the same issue; try rolling back to Chrome 111.

Actually I'm using Andronix on my phone as I don't have a pc. Chrome isn't supported on Andronix as it's ARM64. That's why I have to use chromium and it was actually fine till yesterday. It started showing error this morning.

@Prabh-Saini as I use Andronix, the script WDM gives an error as well on Ubuntu 22.04 (Andronix), that's why I manually installed WD.

**Comment by Prabh-Saini** [comment]
Since its running ARM, I cant really help you as I'm not sure how to fix that. Are you using headless? Try running pyvirtualdisplay.

**Comment by Sellu112** [comment]
Thanks!
