### ISSUE TITLE
how to use proxy

### ISSUE THREAD

**Issue by parthbansal05** [farshadz1997/Microsoft-Rewards-bot#264]
also how to use the proxy, I am new to all this
do I have to select a different country while making the account? and can I be banned for it?
plz give the any important points

**Comment by farshadz1997** [comment]
It's up to you. your proxy must be HTTP/HTTPS and without authentication. you have to enter ```IP:PORT``` in accounts.

**Comment by parthbansal05** [comment]
ok 
any tips on how to create one

**Comment by farshadz1997** [comment]
Ask others about this on Discord
