### ISSUE TITLE
please help with error

### ISSUE THREAD

**Issue by sinulous** [farshadz1997/Microsoft-Rewards-bot#27]
no matter what i try nothing works i've tried the original script and this script, can someone help me with this? i'm using debian linux on ssh
![image](https://user-images.githubusercontent.com/112917229/188534749-1e98f932-be70-4128-adda-7c3440723800.png)

**Comment by dothatdomain1** [comment]
Are you using a Chromebook? If so, have you installed Chromium?

**Comment by sinulous** [comment]
No i’m using debian 11, I only have access to command line

**Comment by farshadz1997** [comment]
Have you tried headless mode? maybe the reason of crashing chrome due to you only have access to terminal and not GUI

**Comment by sinulous** [comment]
when I try google-chrome --headless, output is
`[0906/215451.333786:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0906/215451.347232:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.`

**Comment by farshadz1997** [comment]
Sorry, I couldn't find any fix for your problem

**Comment by Millennium99** [comment]
Had this once on Windows.

Was an error with Chrome. I reinstall Chrome, the chromedriver and upgrade to Python 3.10. That fixed the issue for me @sinulous

**Comment by DerMuffin** [comment]
Can you try to run it with some parameters? Your Screenshot indicates that you only run the script without any paramters (python3 hhh.py)

Try this instead:

python3 MicrosftRewardsBot.py --headless

Check your Accounts.txt. The format should look like in the README File.

Still the same output? @sinulous 

@farshadz1997  Could this Issue be related to something, where the scripts check on which plattform its run? Or doesnt care as long python and chrome is available?

**Comment by farshadz1997** [comment]
@DerMuffin 
> FAST = True # When this variable set True then all possible delays reduced. **<-- This one**

Change FAST to true doesn't force the script to run in headless mode instead you need to remove 
```
if ARGS.headless:  <-- This one at line 65
        options.add_argument("--headless")
```

**Comment by DerMuffin** [comment]
Oh well, my bad...

**Comment by DerMuffin** [comment]
Hey, done some more testing. Seems like the same error also appears when chrome is not installed on the system. At least when i try to run it in the google cloud shell.

You installed the latest chrome package?
