### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Sellu112** [farshadz1997/Microsoft-Rewards-bot#274]
Hey @farshadz1997 @Prabh-Saini  I have 3-4 questions. I hope you won't mind. Thanks in advance!

1. What does '--dont-check-internet' do?Kinda confusing me sorry.
2. Max amount of accounts we can use on same PC (Using different IPs [currently running 6-7 with my IP+UK&US combination and just work fine).
3. And does --redeem automatically puts any random number from script, enter otp (from any website or can be anything)and redeem (or does it work on accounts with already verified numbers. Kinda dumb and stupid que ik).
4. What does proxy do and from where can i get proxies?? Is it same like VPNs but without VPN and using proxies can get our acc suspended??

Also if you could make it more specific for some gcs.
Like "Amazon India", "Amazon US", "Amazon UK", etc so that it doesn't redeem anything sifferent from what we want especially while using VPNs.

Waiting for answers!
Sorry for asking tons of questions. I hope you won't mind.

Also great work @farshadz1997 sir on this script. Really makes things alot more smoother and with no hassle.
And also @Prabh-Saini and other contributors for their contribution on this script

**Comment by farshadz1997** [comment]
Hi,

- 1. The bot checks for the internet connection by pinging on errors so if you don't have Internet it won't open a browser and constantly tries to log in, some devices such as Raspberyy Pi and VPSs doesn't support ping and it leads to error for them, so I added this for those who use this script on mentioned devices.
- 2. TOS said to 6 accounts per household, so I think it's safe to use 6 accounts per IP.
- 3. Redeem works for those accounts which don't require a phone number.

Thanks for appreciation

**Comment by Sellu112** [comment]
> Hi,
> 
> * 1. The bot checks for the internet connection by pinging on errors so if you don't have Internet it won't open a browser and constantly tries to log in, some devices such as Raspberyy Pi and VPSs doesn't support ping and it leads to error for them, so I added this for those who use this script on mentioned devices.
> * 2. TOS said to 6 accounts per household, so I think it's safe to use 6 accounts per IP.
> * 3. Redeem works for those accounts which don't require a phone number.
> 
> Thanks for appreciation

Hey Thanks alot for answering
Could you please answer 4th question as well?

**Comment by farshadz1997** [comment]
Any provider that has HTTP/HTTPS proxy, it depends on the proxies you use, it may cause your account to get banned if it's public. and your proxy must be without authorization.

**Comment by krishwalecha1** [comment]
> Any provider that has HTTP/HTTPS proxy, it depends on the proxies you use, it may cause your account to get banned if it's public. and your proxy must be without authorization.

Thanks alot.
Any website which you use or know?

**Comment by farshadz1997** [comment]
you're welcome. I don't use proxies, you can ask others on Discord.

**Comment by Sellu112** [comment]
> you're welcome. I don't use proxies, you can ask others on Discord.

Thanks!

Also a request, could you make script compatible with Brave browser as it's more private and after disabling trackers, chances of getting accs suspended is less.

**Comment by farshadz1997** [comment]
I'm not sure.

**Comment by desis123** [comment]
> Discord
@farshadz1997 
Do you have any Discord Group ? If so please provide the link , unfortunately I could not find on readme , and other than proxies how do you operate the farmer  , any suggestions will be greatly appreciated .
