### ISSUE TITLE
如何在github的action工作流中设置自动运行该脚本

### ISSUE THREAD

**Issue by wangzhao1124** [farshadz1997/Microsoft-Rewards-bot#283]
我在寻找相关脚本时发现可能是作者您的同学在进行GitHub全自动化运行脚本，想知道这个问题应该如何解决。yml文件应该怎么设置。

**Comment by pro7777777777** [comment]
This is it in English 
When I was looking for related scripts, I found that it might be that the author, your classmate, is running GitHub fully automated scripts, and I want to know how to solve this problem. How should the yml file be set up. ( I think I am not 100% sure)

**Comment by yh-3** [comment]
> Man认真地看到了一个完全英语的github，有英语问题和拉取请求，并决定拿出他的普通话。你至少能做的是谷歌翻译这个问题。除此之外，我不确定如何在 Github Actions 上运行脚本，强烈建议您不要在它上运行，因为它违反了 Github 的服务条款。

I'm wondering, doesn't your country have Google Translate? Or you won't use it. I'm glad to see new people in our country on GitHub, please don't hit a freshman like that.

**Comment by Prabh-Saini** [comment]
> > Man认真地看到了一个完全英语的github，有英语问题和拉取请求，并决定拿出他的普通话。你至少能做的是谷歌翻译这个问题。除此之外，我不确定如何在 Github Actions 上运行脚本，强烈建议您不要在它上运行，因为它违反了 Github 的服务条款。
> 
> I'm wondering, doesn't your country have Google Translate? Or you won't use it. I'm glad to see new people in our country on GitHub, please don't hit a freshman like that.

No, I have access to Google Translate. I'm glad people from across the world are connecting together, I support the access to free open software across the globe, but you have to understand. Every single thing here is written in English, you can't realistically expect everybody else to use google translate when the author could've simply used google translate for his question. I do now notice that this is a relatively new account, and simply request that next time just take a little bit of an understanding of your surroundings. I'm not saying his language is bad or English is good, I'm simply saying that when you're asking for help, the least you could do is remove the language barrier.

**Comment by farshadz1997** [comment]
@wangzhao1124 if you still want to use it, one of the users has made a guide for that. check #244
