### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by NOTScripterBlox** [farshadz1997/Microsoft-Rewards-bot#284]
File "/Downloads/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 348
    or browser.current_url.startswith("https://account.live.com/Abuse"):
    ^^
SyntaxError: invalid syntax

**Comment by farshadz1997** [comment]
sorry for that, Fixed now

**Comment by NOTScripterBlox** [comment]
Thanks
