### ISSUE TITLE
Failed to complete MSN Shopping game

### ISSUE THREAD

**Issue by stym-rj** [farshadz1997/Microsoft-Rewards-bot#287]
Message: element click intercepted: Element <"div style="--i:2" class="shopping-game-card-outline  shopping-game-selected-card">...</div> is not clickable at point (1192, 483). Other element would receive the click: <shopping-modal config-instance-src="default" instance-id="ShoppingModal" data-t="{&quot;n&quot;:&quot;ShoppingModal&quot;,&quot;t&quot;:8}" selectedofferidinmodalnav="72952547692" topcarouselloadtimeskey="1681839772600_72952547692_TopCarousel"></shopping-modal">                                                               
  (Session info: chrome=110.0.5481.177)                                                   
Stacktrace:                                                                               
#0 0x563c24f9fd93 <unknown>                                                               
#1 0x563c24d6e2d7 <unknown>                                                               
#2 0x563c24db1565 <unknown>                                                               
#3 0x563c24daf5a2 <unknown>                                                               
#4 0x563c24dad0ce <unknown>                                                               
#5 0x563c24dac26d <unknown>                                                               
#6 0x563c24d9fff5 <unknown>                                                               
#7 0x563c24dce5f2 <unknown>                                                               
#8 0x563c24d9f873 <unknown>                                                               
#9 0x563c24dce81e <unknown>                                                               
#10 0x563c24de6619 <unknown>                                                              
#11 0x563c24dce353 <unknown>                                                              
#12 0x563c24d9de40 <unknown>                                                              
#13 0x563c24d9f038 <unknown>                                                              
#14 0x563c24ff38be <unknown>                                                              
#15 0x563c24ff78f0 <unknown>                                                              
#16 0x563c24fd7f90 <unknown>                                                              
#17 0x563c24ff8b7d <unknown>                                                              
#18 0x563c24fc9578 <unknown>                                                              
#19 0x563c2501d348 <unknown>                                                              
#20 0x563c2501d4d6 <unknown>                                                              
#21 0x563c25037341 <unknown>                                                              
#22 0x7f960d5c7fd4 <unknown>                                                              
                                                                                          
[MSN GAME] Failed to complete MSN shopping game !

**Comment by farshadz1997** [comment]
there's another issue same to this still open, so I'm closing this.

**Comment by stym-rj** [comment]
> there's another issue same to this still open, so I'm closing this.

can you please link me to that issue so that I can discuss things there?

**Comment by anilabhadatta** [comment]
@farshadz1997 this is probably happening when MSN game is partially completed say 5 questions were answered and then while doing a rerun, the for loop starts from 0 to 10 and the exception is not handled properly when the MSN game is completed midway - say at 5.
Also i would like to know when does MSN game reset since I did this yesterday night around 10PM and i started the script today at 3 Pm and still receiving completed. Only few points were collected today.
