### ISSUE TITLE
Using same phrases for desktop and mobile

### ISSUE THREAD

**Issue by Kwadroo** [farshadz1997/Microsoft-Rewards-bot#29]
Hi,

Great bot and upgrades from the previous bot!

I've noticed that the bot uses some of the same phrases for both desktop and mobile, and therefore that specific phrase does not include the points on the mobile agent.

Is it possible to save used phrases for the day, so it does not use them on the mobile agent. Or use two different sources for phrases  for desktop and mobile?

Cheers and thanks

**Comment by farshadz1997** [comment]
Hi,

There are two sources for searching:

1.  get words from Random word package
2.  Google trends

When the API fails in getting random words, then it uses Google Trends. In your case, random words may not work, so it uses Google Trends on PC and mobile, which are the same.

I'll search to if find more resources or not.

**Comment by Kwadroo** [comment]
Thanks for the reply.

I changed connection, and it now works perfectly.

Thanks for developing this :-)
