### ISSUE TITLE
Your email/password was invalid - The issue was resolved by executing javascript

### ISSUE THREAD

**Issue by taisport** [farshadz1997/Microsoft-Rewards-bot#294]
I'm not sure why the code 
CODE :
browser.find_element(By.NAME, "loginfmt").send_keys(email) 

is unable to send the complete email address to sign in. However, you can use the following code snippet with execute_script to set the complete email address in the input field:

CODE:
input_field = browser.find_element(By.ID, "i0116")
browser.execute_script("arguments[0].value = arguments[1];", input_field, email)

This code will set the value of the input_field element to the email variable, allowing you to send the complete email address in the sign-in form.

**Comment by farshadz1997** [comment]
yeah, I know I can use that but the main question is why it's not working for you.

**Comment by taisport** [comment]
I also want to know why the email address not complete. 

E.g 
account should be "abcdef01005@outlook.com"

finally the input is "abcdef0@outlook.com".

**Comment by farshadz1997** [comment]
Use --error to check what's the problem
