### ISSUE TITLE
Cannnot run .bat files on Win11

### ISSUE THREAD

**Issue by FlyMe2TheYue** [farshadz1997/Microsoft-Rewards-bot#295]
Sorry,English is not my native language; please excuse typing errors.
I ran the following commands in terminal:

pip install -r requirements.txt
ren accounts.json.sample accounts.json
echo "py .\ms_rewards_farmer.py --redeem --session" > manual_run.bat
echo "py .\ms_rewards_farmer.py --start-at 06:30 --everyday --redeem --session" > run_at_6.30am_daily.bat
echo "py .\ms_rewards_farmer.py --redeem --session --edge" > manual_run_edge.bat
echo "py .\ms_rewards_farmer.py --start-at 06:30 --everyday --redeem --session --edge" > run_at_6.30am_daily_edge.bat
echo "py .\ms_rewards_farmer.py --calculator" > calculator.bat

When I ran .bat files, it shows "The system cannot find the specific path."
I tried to change the path,even deleted words after ms_rewards_farmer.py in commands(I recognized that was stupid.).
Would you give me a pointer to a good explanation of this,please?

System Information:(Copied from Settings)
版本	Windows 11 家庭中文版 Insider Preview
版本	22H2
安装日期	‎2023/‎4/‎10
操作系统版本	25336.1010
体验	Windows Feature Experience Pack 1000.25336.1010.0

Python version 3.11 64-bit

![05INDHL}~R6@H{7ZQ$RGEI0](https://user-images.githubusercontent.com/128036906/233801030-516fe305-5974-4b07-a556-efa35de4b484.png)

**Comment by farshadz1997** [comment]
Remove double quotes at start and end just type ```py ms_rewards_farmer.py --session --redeem```

**Comment by FlyMe2TheYue** [comment]
Thank you very much!It works exactly!
But there is a new issue.Bot tried to login but I have Microsoft Authenticator APP,and Chrome closed the webpage immediately before I approve.I wonder if it is necessary to disable MA?

**Comment by farshadz1997** [comment]
Yes, it's necessary to turn off 2FA

**Comment by FlyMe2TheYue** [comment]
farshadz1997,thank you for your help!Bot works successfully!
