### ISSUE TITLE
Stuck on "Ensuring login on Bing"

### ISSUE THREAD

**Issue by forevierre** [farshadz1997/Microsoft-Rewards-bot#3]
Screenshot below:
![image](https://user-images.githubusercontent.com/100557011/159615725-a373abcc-eafa-40a6-ab2d-3ec5ae3429e5.png)

**Comment by forevierre** [comment]
It raised a time out and restarted, but still the same result, and it goes on and on:
![image](https://user-images.githubusercontent.com/100557011/159616552-d78b43ab-d506-4f19-a3f4-b318c2da46b8.png)

**Comment by farshadz1997** [comment]
Could you please attach source of your Bing and your Microsoft Rewards page?

**Comment by forevierre** [comment]
Sorry, not sure what you mean by source?

**Comment by farshadz1997** [comment]
I mean HTML code of pages that I mentioned.

**Comment by forevierre** [comment]
It actually works the first time I run it, but it doesn't do the mobile searches, and instead does the looping I mentioned above. I haven't tried with another account.

HTML for Bing: https://pastebin.com/Unbn2WM7
HTML for Rewards page:
[Rewards.txt](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/8354399/Rewards.txt)

**Comment by farshadz1997** [comment]
Your Rewards page looks good but in your Bing page **Accept cookies popup** is interfering with **Menu button** and blocked it. are you using custom **user-agent** for mobile? if yes what is that?

**Comment by forevierre** [comment]
Nope, I'm not. Could it be due to adblockers or whatnot? Thanks for your help btw.

**Comment by farshadz1997** [comment]
if your adblocker is chrome extension then it is not because Web driver create clean session, but if you have third party adblocker software try to turn it off and test it again.

**Comment by forevierre** [comment]
I don't run any adblockers aside from chrome extensions, so that's probably not it.

**Comment by farshadz1997** [comment]
Could you please try with this one, I added a script to remove cookies popup.
[ms_rewards_farmer.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/8387573/ms_rewards_farmer.zip)

**Comment by forevierre** [comment]
This worked perfectly! Thank you so much for your help!
