### ISSUE TITLE
not getting creidts pls help

### ISSUE THREAD

**Issue by thefakeknightstellar** [farshadz1997/Microsoft-Rewards-bot#317]
I am not getting any credits plz help.
![image](https://user-images.githubusercontent.com/132127180/235292561-3f0b992c-f70b-48b3-afa9-f6cc7e8f077c.png)

I have like 3 accounts. This is the log of the oldest account. It was running for some time but it didnt get ANY credits. the farm worked fine for some days and all of a sudden for the past like 2 days it doesnt get any credits. 
![image](https://user-images.githubusercontent.com/132127180/235292434-b401d93f-9390-4550-85a8-0b1937d68ab2.png)
this is the log of my second account. usually it gets like 300 credits per day (i have proof) and now its like getting only a hundred. 

this is my 3rd account: 
![image](https://user-images.githubusercontent.com/132127180/235292600-1e6d7f62-acf3-4197-9b44-a82fbdbcbf3e.png)
no credits earnt.  

when i searched manually, it didnt credit when using the same terms so i changed ALL of the search words and i am still not getting anything

this is the thing i use for running the script (i tried edge too, same results)

`python3 ms_rewards_farmer.py --session --superfast --no-images --shuffle --everyday --error --discord https://discord.com/api/webhooks/xxxxxxxx --skip-unusual --skip-shopping --virtual-display`

the worked well previously

**Comment by thefakeknightstellar** [comment]
I am running this script in a cloud VPS with 16 GB RAM and good processor. As I said, all was working fine earlier (like 5-6 days) and now it just became very slow. I do not know why

**Comment by farshadz1997** [comment]
If you're running your accounts in two regions, you should know that Microsoft blocked grinding points from multiple countries.

**Comment by juanplayerofc** [comment]
> If you're running your accounts in two regions, you should know that Microsoft blocked grinding points from multiple countries.

Since when?

**Comment by farshadz1997** [comment]
@juanplayerofc few days ago

**Comment by thefakeknightstellar** [comment]
> If you're running your accounts in two regions, you should know that Microsoft blocked grinding points from multiple countries.

How does it work? so if i started grinding in us then does it not work in other regions permenantly or does it not work for that specific day?

**Comment by Aashu-sm** [comment]
> 

if you are with one region stick with it. it's the only solution

**Comment by thefakeknightstellar** [comment]
> > 
> 
> if you are with one region stick with it. it's the only solution

should i abandon the earnings from existing accounts and create new accounts and stick with 1 region or can i just use my existing accounts but like only use 1 region

**Comment by thefakeknightstellar** [comment]
> > > 
> > 
> > 
> > if you are with one region stick with it. it's the only solution
> 
> should i abandon the earnings from existing accounts and create new accounts and stick with 1 region or can i just use my existing accounts but like only use 1 region

I did a few modifications to search words and then I changed stuff in the python file and now i dont think im encountering any issue

**Comment by Aashu-sm** [comment]
> > > > 
> > > 
> > > 
> > > if you are with one region stick with it. it's the only solution
> > 
> > 
> > should i abandon the earnings from existing accounts and create new accounts and stick with 1 region or can i just use my existing accounts but like only use 1 region
> 
> I did a few modifications to search words and then I changed stuff in the python file and now i dont think im encountering any issue
working with multiple regions 

> > > > 
> > > 
> > > 
> > > if you are with one region stick with it. it's the only solution
> > 
> > 
> > should i abandon the earnings from existing accounts and create new accounts and stick with 1 region or can i just use my existing accounts but like only use 1 region
> 
> I did a few modifications to search words and then I changed stuff in the python file and now i dont think im encountering any issue

working with multiple regions or just the issue got fixed

**Comment by Aashu-sm** [comment]
> > > 
> > 
> > 
> > if you are with one region stick with it. it's the only solution
> 
> should i abandon the earnings from existing accounts and create new accounts and stick with 1 region or can i just use my existing accounts but like only use 1 region

no need to abandon that account
