### ISSUE TITLE
ERROR] No search terms found, account skipped

### ISSUE THREAD

**Issue by JittoJoseph** [farshadz1997/Microsoft-Rewards-bot#318]
You said you fixed it in cf5dcbe.
But it didn't resolve the issue.
I am now getting even more errors.

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 585 points on your account !
File "/home/runner/work/mineflayer/mineflayer/ms_rewards_farmer.py", line 2704, in farmer
    remainingSearches, remainingSearchesM = getRemainingSearches(

  File "/home/runner/work/mineflayer/mineflayer/ms_rewards_farmer.py", line 1628, in getRemainingSearches
    counters['pcSearch'][1]['pointProgress']
list index out of range

And then it skips to the next account.
And that account gets the same error,
At last the log in Discord will be 0 points earned today.

**Comment by thefakeknightstellar** [comment]
I am getting the same 0 points earned today thing but for certain accounts, I am actually earning stuff. I am also not getting error ( i have error flag turned on)

**Comment by farshadz1997** [comment]
What is the region of your accounts? I checked the code and it's working well for US.

**Comment by JittoJoseph** [comment]
US works fine,
But I run both US and UK.
I tried the bot with US, UK , canada and some other regions,
But it works only with US.

and yes I am running it on GitHub, as I found a way to use VPN for free on git actions

**Comment by farshadz1997** [comment]
I can't help you for other regions, I don't have access to others countries data

**Comment by JittoJoseph** [comment]
It was working untill like 2-3 days ago, so I guess a recent update broke the bot's support for other regions,
Could you see what's wrong using a vpn?

**Comment by anilabhadatta** [comment]
@farshadz1997 Can you implement Fitness Videos point collection? 40 points/day can be earned by watching very short videos.
https://www.reddit.com/r/MicrosoftRewards/comments/11nqkye/new_list_of_ultra_low_time_fitness_points/
Refer to this post for video links and the URL can be changed to any region and the video will load without any issues.

**Comment by Aashu-sm** [comment]
> I am getting the same 0 points earned today thing but for certain accounts, I am actually earning stuff. I am also not getting error ( i have error flag turned on)
> 
> btw r u doing this in github/gitlab actions?

its because of using multiple ips for the same acc, its also because of us(indians and our very dear youtubers also because of a motherfuckers tweet)

**Comment by farshadz1997** [comment]
I'm closing this as I cannot help with that

**Comment by farshadz1997** [comment]
I'm closing this as I cannot help with that

**Comment by JittoJoseph** [comment]
There is a possibility that some changes made on April 26th or 27th broke the bot,
Could you look into that?

**Comment by JittoJoseph** [comment]
looks like microsoft is fixing their stuff.
its not an issue with the bot, 
we can no longer farm points in multiple regions.
