### ISSUE TITLE
Output of streakday

### ISSUE THREAD

**Issue by kobi-wan** [farshadz1997/Microsoft-Rewards-bot#32]
Hi,
is it possible to output the day of streak? In the past I lost my streak a few times. Because of this I have to check the rewards page every day to see, if all daily tasks were done.
So it would be nice to see in the output, if the streak was increased after script is finished with the tasks.

**Comment by farshadz1997** [comment]
Hi, sorry for delay
I'll add it in next updates

**Comment by farshadz1997** [comment]
I added error message if bot fails on daily quests so you can find out your daily streaks did not increase.

**Comment by kobi-wan** [comment]
Hi,
in the last commit, you removed the streakday part, but why?

By the way, it wasn't showing the correct value. Instead of  `["coachMarks"]["streaks"]["promotion"]["activityProgress"]` it should read `["streakPromotion"]["activityProgress"]` Json value.

**Comment by farshadz1997** [comment]
Hi,
I removed it because it didn't show the correct value when all daily quests completed, so it was useless. but there's a flag that shows if any of quizzes fails then it displays daily set did not complete successfully.
I'll look into the value you mentioned.
