### ISSUE TITLE
"Daily Set failed, streak not increased." (US)

### ISSUE THREAD

**Issue by Aashu-sm** [farshadz1997/Microsoft-Rewards-bot#321]
single IP/region(US)

any fix for this problem sir

[LOGIN] Account already logged in !
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 1775 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completing search of card 1
[DAILY SET] Completing quiz of card 2
[DAILY SET] Completing poll of card 3
File "/home/runner/work/batch-1/batch-1/bot.py", line 1140, in completeDailySet
    completeDailySetSurvey(cardNumber)

  File "/home/runner/work/batch-1/batch-1/bot.py", line 913, in completeDailySetSurvey
    waitUntilClickable(browser, By.ID, "btoption0", 15)

  File "/home/runner/work/batch-1/batch-1/bot.py", line 645, in waitUntilClickable
    WebDriverWait(browser, time_to_wait).until(

  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
Message: 
Stacktrace:
#0 0x55c7b5a95fe3 <unknown>
#1 0x55c7b57d4d36 <unknown>
#2 0x55c7b5811c4d <unknown>
#3 0x55c7b5811d61 <unknown>
#4 0x55c7b584d6a4 <unknown>
#5 0x55c7b58328ed <unknown>
#6 0x55c7b584b232 <unknown>
#7 0x55c7b5832693 <unknown>
#8 0x55c7b580503a <unknown>
#9 0x55c7b580617e <unknown>
#10 0x55c7b5a57dbd <unknown>
#11 0x55c7b5a5bc6c <unknown>
#12 0x55c7b5a654b0 <unknown>
#13 0x55c7b5a5cd63 <unknown>
#14 0x55c7b5a2fc35 <unknown>
#15 0x55c7b5a80138 <unknown>
#16 0x55c7b5a802c7 <unknown>
#17 0x55c7b5a8e093 <unknown>
#18 0x7fbf2c1f5b[43](https://github.com/regb1/batch-1/actions/runs/4834607847/jobs/8616029402#step:7:44) <unknown>

[DAILY SET] Daily Set did not completed successfully ! Streak not increased
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !

**Comment by Aashu-sm** [comment]
i think issue got fixed if it ocurs again i will reopen the issue

**Comment by farshadz1997** [comment]
These kinds of issues most of the time come from MS, don't create a new issue for these whenever you see an error.

**Comment by Aashu-sm** [comment]
> These kinds of issues most of the time come from MS, don't create a new issue for these whenever you see an error.

will do that, sorry for the inconvenience, i faced this error for first time, thanks for the info sir.
