### ISSUE TITLE
Shifting Tabs Solution 

### ISSUE THREAD

**Issue by Chappie18** [farshadz1997/Microsoft-Rewards-bot#326]
If you can use the technique to open every tab for a promotion at once in a separate window.
It easily completes the promotion tasks.

For now, I'm currently opening each additional promotion tab manually by pressing Ctrl+Promotion tabs.
opening the right-most tab, waiting five seconds, and then pressing Ctrl+W to delete each tab.

**Comment by farshadz1997** [comment]
the thing you say can not be implemented in the bot easily, it requires the Async method or multi-threading.

**Comment by Chappie18** [comment]
Yes, no issue
I just shared the temporary fixes I found with you so you could include them in your list of potential solutions.
