### ISSUE TITLE
HELP ME PLSSSSSS

### ISSUE THREAD

**Issue by Hankypoo7** [farshadz1997/Microsoft-Rewards-bot#328]
how do i run this in codespaces pls help im an idiot

**Comment by Aashu-sm** [comment]
wen read readme.md

**Comment by Hankypoo7** [comment]
@Aashu-sm  Im 13 it makes no sense im confused

**Comment by Aashu-sm** [comment]
> 
i am very sure that you have a pc, if you have a pc then alslo know computer basics, but thats not enough you learn about CLI first

**Comment by Aashu-sm** [comment]
bro this thing is not for you then, first learn basics..

**Comment by Hankypoo7** [comment]
what basics

**Comment by Hankypoo7** [comment]
what do i have to learn first

**Comment by Hankypoo7** [comment]
thanks
