### ISSUE TITLE
[Bug] --session --edge doesn't work well

### ISSUE THREAD

**Issue by zSavT** [farshadz1997/Microsoft-Rewards-bot#331]
Using --session and --edge doesn't work well.
When the first account is finished, the account doesn't log out and the bot does not recognize this and continues to do operations for the second account even if the first one is logged in on edge.

**Comment by farshadz1997** [comment]
It's because you have already signed in to your account on Edge, first you need to log it out from Windows and then run it. I recommend you use Chrome instead Edge.
