### ISSUE TITLE
mobile searches are getting stuck

### ISSUE THREAD

**Issue by yoyodolo** [farshadz1997/Microsoft-Rewards-bot#34]
mobile searches are getting stuck on this:
![image](https://user-images.githubusercontent.com/34823653/196223487-d7419954-3f6a-4202-9d98-8f088de7aecc.png)

**Comment by farshadz1997** [comment]
Could you please upload the source of page in your GitHub gist whenever that Bing app banner at top appears.

**Comment by yoyodolo** [comment]
i'm sorry, can you please guide me for that?

**Comment by macrosalt** [comment]
i encounter the similar issue. during `checkBingLogin`, the account wont show when accessing `bing.com`. need to click on the login button then the account will display @farshadz1997 
<img width="1745" alt="image" src="https://user-images.githubusercontent.com/8212479/196479022-b3762a74-3d8a-4b11-a40d-c285c4a77ae8.png">

**Comment by farshadz1997** [comment]
> [source.txt](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/9815600/source.txt) here's my source, with the same problem. I renamed it from .html if that matters btw

@leem919 sorry, I can't use this it opens as text file in my browser, I want to open it as a page

**Comment by farshadz1997** [comment]
> [source.txt](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/9834036/source.txt) Alright, I got it to open as a web page.

Thanks, but this time the banner you mentioned above not in your file

**Comment by farshadz1997** [comment]
Never mind, I get the banner on my browser, I'll fix it soon.
