### ISSUE TITLE
I keep getting this error ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by TrickyTay** [farshadz1997/Microsoft-Rewards-bot#341]

**Comment by zSavT** [comment]
Did you open the shell in the correct directory (the root of the repo)? Did you use `pip install -r .\requirements.txt`?

**Comment by AkhilProto** [comment]
You have to execute the command in the correct directory as zSavT said. Like for example my laptop has the ms-farmer files in G drive(G:\microsoft-rewards-bot), so in CMD my prompt should look like this.

``G:\microsoft-rewards-bot> ``  ``pip install -r .\requirements.txt``
