### ISSUE TITLE
Script waiting for login page while it is already logged in

### ISSUE THREAD

**Issue by AkhilProto** [farshadz1997/Microsoft-Rewards-bot#342]
When I execute the script, it opens the web page and waits for the login page even if it is already logged in. My laptop(Windows) logs into all of the microsoft websites automatically. I know I can just log out manually, but when i went through the code, i noticed that there is a function in the script which checks if the user has already signed into the rewards webpage, So what is the use of the function in the script.
`def checkBingLogin():`

And my laptop is also slow and takes time to load the webpage, so its difficult for me to manually log out of all the webpage .

**Comment by farshadz1997** [comment]
bot needs to get the confirmation that you are still logged in on Bing

**Comment by AkhilProto** [comment]
> bot needs to get the confirmation that you are still logged in on Bing

Ya it's not working
