### ISSUE TITLE
Use proxy only when logging in

### ISSUE THREAD

**Issue by C63H88CoN14O14P** [farshadz1997/Microsoft-Rewards-bot#345]
Hello author, I have encountered some issues while using your bot recently. Just a few days ago, my reward account that I have been using for a long time did not increase any reward points when completing tasks on foreign networks(proxies), only increasing points when completing tasks on local networks.
  However, due to the special network environment in my country, logging into Microsoft accounts is very slow and sometimes cannot be loaded. Therefore, I hope to add a parameter so that the bot can use proxies only when logging into Microsoft accounts and not use them when performing tasks.
  The problem I encountered may be uncommon, but I still hope that you can add this parameter to the script.
  Thank you very much.

**Comment by farshadz1997** [comment]
Hello, It's not possible, if you were farming from two country you should know that Microsoft blocked this way that's why you didn't earn points, stick to one country

**Comment by C63H88CoN14O14P** [comment]
> Hello, It's not possible, if you were farming from two country you should know that Microsoft blocked this way that's why you didn't earn points, stick to one country

Hello, it seems that you have misunderstood my meaning. I do not wish to use two countries' proxy servers with one account to obtain double points. The problem I am currently facing is that logging into my Microsoft account using my country's network is too slow (sometimes it doesn't even load), so I hope to use a proxy server from another country to speed up the login process while still using my own country's network for farming. I hope you can understand.Thanks.

**Comment by farshadz1997** [comment]
I understand that, but as far as I know, it's impossible to disable the proxy after the browser instance is created.
