### ISSUE TITLE
Stuck on "ensuring login on bing" sometimes

### ISSUE THREAD

**Issue by leem919** [farshadz1997/Microsoft-Rewards-bot#35]
![image](https://user-images.githubusercontent.com/8106607/196566211-86691cd5-10c8-4375-b1cb-eb2aa0b15b92.png)

When the rewards counter appears on the side like this, the bot hangs and keeps refreshing, however it happened to revert back to the old way it looked after timing out and the bot continued. I think they'll be updating to the newer one eventually though.

**Comment by beenruuu** [comment]
I have this problem

**Comment by Conirefle** [comment]
Same problem, need to restart the script to aovid this problme

**Comment by farshadz1997** [comment]
I'll fix it as soon as I get the update same as you
