### ISSUE TITLE
MSN Fitness videos

### ISSUE THREAD

**Issue by JittoJoseph** [farshadz1997/Microsoft-Rewards-bot#350]
```
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

def browserSetup(headless=True, user_agent=None):
    options = webdriver.ChromeOptions()
    options.headless = headless

    if user_agent:
        options.add_argument(f'user-agent={user_agent}')

    browser = webdriver.Chrome(options=options)
    return browser

browser = browserSetup(False, PC_USER_AGENT)
video_url = "https://www.msn.com/en-gb/health/fitnessworkoutvideo/how-to-do-a-bench-dip-video-dailymotion-x546il5?ocid=entnewsntp&ChallengeId=30-day-weight-loss-challenge-mark-sneddon&type=fitnesschallenge&cvid=466eca9f7f4248b3852dcce38181e7f3"

browser.get(video_url)

# Wait for the video element to be present
video_element = WebDriverWait(browser, 10).until(
    EC.presence_of_element_located((By.ID, "dmp_Video"))
)

video_duration = video_element.get_attribute("duration")
if video_duration:
    video_duration = int(video_duration)

if video_duration:
    time.sleep(video_duration)

print("Video watching completed.")

```

https://www.reddit.com/r/MicrosoftRewards/comments/11nqkye/new_list_of_ultra_low_time_fitness_points/?sort=new
this reddit post has a lot of links for fitness videos . 
could you add this feature.
the fitness videos reset very 10 days, so make a'n array of 10 links, and put a day count in the accounts.json
every day it should take the day count and get the correct video from the array, also the day count should reset to 1 when it is at more than 10.
also i didn't really know how to acquire the video duration .

**Comment by JittoJoseph** [comment]
in the code i have put only 1 link, so if you are doing this then make an array of 10 links.
something like this
```
links = [
    'https://example.com/link1',
    'https://example.com/link2',
    'https://example.com/link3',
    'https://example.com/link4',
    'https://example.com/link5',
    'https://example.com/link6',
    'https://example.com/link7',
    'https://example.com/link8',
    'https://example.com/link9',
    'https://example.com/link10'
]

def send_request_to_link(links, current_day):
    link_index = (current_day - 1) % len(links)
    link_to_send = links[link_index]
    response = requests.get(link_to_send)
    print(f"Sent request to {link_to_send}. Response: {response.text}")

def get_last_executed_day():
    try:
        with open('last_executed_day.txt', 'r') as file:
            last_executed_day = int(file.read())
    except FileNotFoundError:
        last_executed_day = 0

    return last_executed_day

def update_last_executed_day(current_day):
    with open('last_executed_day.txt', 'w') as file:
        file.write(str(current_day))

def main():
    today = datetime.date.today()
    current_day = today.day
    last_executed_day = get_last_executed_day()

    if current_day != last_executed_day + 1:
        current_day = 1

    send_request_to_link(links, current_day)
    update_last_executed_day(current_day)
    ```

**Comment by JittoJoseph** [comment]
Could someone tell me how you can get the duration of the video in this link using python?
https://www.msn.com/en-gb/health/fitnessworkoutvideo/how-to-do-a-bench-dip-video-dailymotion-x546il5?ocid=entnewsntp&ChallengeId=30-day-weight-loss-challenge-mark-sneddon&type=fitnesschallenge&cvid=466eca9f7f4248b3852dcce38181e7f3

**Comment by richardrun** [comment]
manually add the length as a data

**Comment by JittoJoseph** [comment]
All the links in an array will have different lengths.
So I need to do it auto

**Comment by niklasbaranski** [comment]
> ll me how you can get the duration of the video in this link

have to look for this:
![image](https://github.com/farshadz1997/Microsoft-Rewards-bot/assets/87082036/587292ac-ac7f-4c04-a1ca-809d43949b83)


you can also use this to get your current progress, so you could also build an estimated time function, which would be pretty cool
![image](https://github.com/farshadz1997/Microsoft-Rewards-bot/assets/87082036/9d5c8035-f86d-495e-8ece-47b3074987e8)
