### ISSUE TITLE
Multiple bot farming ad otnce (parallel) «logs»

### ISSUE THREAD

**Issue by Conirefle** [farshadz1997/Microsoft-Rewards-bot#37]
![image](https://user-images.githubusercontent.com/34823518/197335378-0c2c50d4-d137-4b54-a7e1-a4c8297fd762.png)
Hi again,
Love your work and using it with close to 0 programming kwoledge, it's very straight forward and thanks of that.
With a friend (he speaks python too), we menaged to skip the first "enter" request as you open the file, and with a .bat file i can finally open all the scripts with a double click.
Coming to the issue, I don't know why is being created only 1 logs_account.txt in the directory of the batch file instead of the directory of the scripts. I hope i explained myslef. Are you plannig on doing a multiple bot with this fix? Thanks anyways (w/o the log is usable but not optimal obv)
![image](https://user-images.githubusercontent.com/34823518/197335651-41bbbd19-29fe-4629-89d2-d2fa27e3d616.png)
![image](https://user-images.githubusercontent.com/34823518/197335674-98180e38-6e8b-4df5-94cb-39d3e4bc8215.png)
<3

**Comment by farshadz1997** [comment]
Hi,
It's not a good idea as it makes system almost unusable for most people.
why don't you get copy of your edited script in multiple folders and run all of them manually.
when you use .bat file to run the script, it uses .bat directory to create logs not the bot directory itself.

**Comment by Conirefle** [comment]
hi again,
am already doing as you said, and it's working. Just trying to understand how i can avoid the log problem.
btw if anyone need it here it is the super simple script 
![image](https://user-images.githubusercontent.com/34823518/198098333-78c3cc3e-e94f-455d-a6b1-3409d9a358b8.png)

**Comment by farshadz1997** [comment]
I need to edit script to solve your problem.

**Comment by farshadz1997** [comment]
tell me if you still have problem with logs

**Comment by beenruuu** [comment]
> ![image](https://user-images.githubusercontent.com/34823518/197335378-0c2c50d4-d137-4b54-a7e1-a4c8297fd762.png)
> 
> Hi again,
> 
> Love your work and using it with close to 0 programming kwoledge, it's very straight forward and thanks of that.
> 
> With a friend (he speaks python too), we menaged to skip the first "enter" request as you open the file, and with a .bat file i can finally open all the scripts with a double click.
> 
> Coming to the issue, I don't know why is being created only 1 logs_account.txt in the directory of the batch file instead of the directory of the scripts. I hope i explained myslef. Are you plannig on doing a multiple bot with this fix? Thanks anyways (w/o the log is usable but not optimal obv)
> 
> ![image](https://user-images.githubusercontent.com/34823518/197335651-41bbbd19-29fe-4629-89d2-d2fa27e3d616.png)
> 
> ![image](https://user-images.githubusercontent.com/34823518/197335674-98180e38-6e8b-4df5-94cb-39d3e4bc8215.png)
> 
> <3

Hello Conirefle, do you have Discord or another method to contact with you i need to ask you various things, thanks my discord is beenruuu#0800
