### ISSUE TITLE
New web driver is initialized for each account while running with --session option

### ISSUE THREAD

**Issue by abhay-x** [farshadz1997/Microsoft-Rewards-bot#387]

**Comment by abhay-x** [comment]
so it is utilize 100% cpu resource after farming few accounts.

**Comment by farshadz1997** [comment]
what is your web driver version? and it creates what exactly?

**Comment by abhay-x** [comment]
for every account farming a new web driver is initialized, as i noticed in tasks, my edge web driver version is 113.0.1774.42

**Comment by farshadz1997** [comment]
how about chrome web driver?
