### ISSUE TITLE
Send log Logs_account to Telegram

### ISSUE THREAD

**Issue by beenruuu** [farshadz1997/Microsoft-Rewards-bot#39]
Is it possible to send a record of logs_account to a telegram or discord bot and be able to see the record of points obtained? If so, how can I do it?

**Comment by farshadz1997** [comment]
It's not possible currently but I will work on it.

**Comment by farshadz1997** [comment]
@beenruuu get the latest version and install requirements again then use `--telegram <TOKEN> <CHAT_ID>` to send logs to your account.
