### ISSUE TITLE
Bat file instantly closes

### ISSUE THREAD

**Issue by Ducky443747** [farshadz1997/Microsoft-Rewards-bot#399]
As soon as I double click to open the bat file, it just instantly closes and I can't seem to get it to work. This happens with the calculator too and I have no idea of how to fix it

**Comment by Ducky443747** [comment]
I forgot to mention I do have python and pip and it seemed fine while installing

**Comment by farshadz1997** [comment]
how about running it without bat file?

**Comment by farshadz1997** [comment]
you can open ms_rewards_farmer.py by just double clicking on it, or open terminal in the bot directory and type ```python ms_rewards_farmer.py``` You may want to use args if you open with terminal.

**Comment by Ducky443747** [comment]
ok thank you, ill have to test when I get back home, if it works i can close this

**Comment by Ducky443747** [comment]
Also, how do I run the calculator and stuff?

**Comment by Ducky443747** [comment]
it works now, thanks!
