### ISSUE TITLE
Crash related to ChromeDriver

### ISSUE THREAD

**Issue by ryansg8** [farshadz1997/Microsoft-Rewards-bot#4]
![image](https://user-images.githubusercontent.com/12075053/160659202-03f83787-9436-41c1-9f67-7c01f7c843f2.png)

Really not sure what this is about. All I did was apt install chrome driver.

**Comment by farshadz1997** [comment]
Hi, I changed few thing for you, please test it.
[ms_rewards_farmer.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/8403134/ms_rewards_farmer.zip)

**Comment by ryansg8** [comment]
> Hi, I changed few thing for you, please test it. [ms_rewards_farmer.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/8403134/ms_rewards_farmer.zip)

Yes this works for me now, thank you!
