### ISSUE TITLE
keep getting error when writing password after update

### ISSUE THREAD

**Issue by p0d9K** [farshadz1997/Microsoft-Rewards-bot#402]
I run the script on a ubuntu 20.04 vps, the script was running correctly until selenium stealth was added. Now it keeps stuck on writing password and getting this.
The network has no problem, and older version is still able to run

```
File "/root/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2723, in farmer
    login(browser, account['username'], account['password'], account.get(

  File "/root/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 353, in login
    browser.find_element(By.ID, 'idBtn_Back').click()

  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webelement.py", line 88, in click
    self._execute(Command.CLICK_ELEMENT)

  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webelement.py", line 396, in _execute
    return self._parent.execute(command, params)

  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)

  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=113.0.5672.126)
Stacktrace:
#0 0x55aa39404b93 <unknown>
#1 0x55aa3915bc86 <unknown>
#2 0x55aa391457f4 <unknown>
#3 0x55aa39145540 <unknown>
#4 0x55aa3914400c <unknown>
#5 0x55aa391447a2 <unknown>
#6 0x55aa391521af <unknown>
#7 0x55aa39153252 <unknown>
#8 0x55aa39165a24 <unknown>
#9 0x55aa3916a20b <unknown>
#10 0x55aa39144c37 <unknown>
#11 0x55aa3916584b <unknown>
#12 0x55aa391cefe6 <unknown>
#13 0x55aa391b6a23 <unknown>
#14 0x55aa3918bae8 <unknown>
#15 0x55aa3918cbbe <unknown>
#16 0x55aa393c9276 <unknown>
#17 0x55aa393cc625 <unknown>
#18 0x55aa393cce45 <unknown>
#19 0x55aa393d4b2e <unknown>
#20 0x55aa393cd52c <unknown>
#21 0x55aa393a4781 <unknown>
#22 0x55aa393ed1c8 <unknown>
#23 0x55aa393ed373 <unknown>
#24 0x55aa393fd485 <unknown>
#25 0x7fa6b62b6609 <unknown>
```

**Comment by Jinghao-Tu** [comment]
same problem

**Comment by p0d9K** [comment]
> Can you do it manually and tell me what page comes after writing the password? send a screenshot, please.

I run this on vps using --virtual-display, so I think I can use x11vnc to connect to it to take a screenshot.
but after I installed x11vnc and run the script, I no longer get this error anymore, the script runs correctly now. I don't even need to manually run x11vnc or something, just installed x11vnc and this error is gone.

**Comment by p0d9K** [comment]
> Can you do it manually and tell me what page comes after writing the password? send a screenshot, please.

Unfortunately, this error happened again...but I managed to take a screenshot.
I have updated script to the latest version, and this is the command I use:
python3 ms_rewards_farmer.py --virtual-display --no-webdriver-manager --superfast --discord https://discord.com/api/webhooks --print-to-webhook
[https://imgur.com/E7v08rR](url)

**Comment by p0d9K** [comment]
I tried on a better vps, and there were no problems. It seems it really was a network issue. I should be more cautious when choosing VPS providers.
