### ISSUE TITLE
 Discord server down or me get banned ?

### ISSUE THREAD

**Issue by merlin7vv4** [farshadz1997/Microsoft-Rewards-bot#404]
i cant find

**Comment by farshadz1997** [comment]
my account got disabled

**Comment by farshadz1997** [comment]
on that case contact me on telegram

**Comment by Afuhuu** [comment]
> on that case contact me on telegram

Your telegram I'd?

**Comment by farshadz1997** [comment]
> > on that case contact me on telegram
> 
> Your telegram I'd?

I have put it on my profile

**Comment by farshadz1997** [comment]
join here on Telegram: https://t.me/MRF_FZ
