### ISSUE TITLE
Redeeming Points

### ISSUE THREAD

**Issue by You-Dont-Gnome** [farshadz1997/Microsoft-Rewards-bot#41]
Have any of you successfully redeemed any points?

We a ran a LOT of accounts over many different computers, networks and VPNs.

We had many accounts over 10,000 points - when trying to redeem for a gift card it says 'There's been an issue with your Microsoft Account or order - please contact our customer service team'.

If you contact customer service team then they suspend your account right away. Out of countless accounts - we didn't get a single one that allowed us to redeem a code.

Has anyone else experienced this?

**Comment by DerMuffin** [comment]
@You-Dont-Gnome 

How many Accounts you running per IP? <-- Should be not more than 6

Do you use outlook mails for your accounts? <-- Much more likely to get banned

Another Issue can be that farming and redeem points on too different locations. Like other countrys. I also add as less information to a account as possible. No names, no phone numbers etc.

Also try different tel numbers while redeem a reward. If you use the same number over and over and different accounts in a short time they also get banned.

Hope this helped a bit

**Comment by robotelro** [comment]
Redeem directly from reward app on xbox, that works for me every time, max 25$. when you try 50 you get banned, because...

**Comment by DerMuffin** [comment]
Hey @You-Dont-Gnome ,

another idea is to use a different script with auto redeem feature. Maybe this works better for you. Link is in my open issue

**Comment by OwnerCM** [comment]
I have the same problem. I didn't contact customer service after the order was rejected, and I'm afraid of blocking my account. Currently, there is no good solution. I have temporarily stopped using the tool to obtain points, and I hope it can be restored.
