### ISSUE TITLE
Computer goes to sleep

### ISSUE THREAD

**Issue by Ducky443747** [farshadz1997/Microsoft-Rewards-bot#415]
I tried to set the bot to run everyday, but my laptop keeps falling asleep before it can run at said time. Is there any way to fix this or do I have to set it to never sleep? Also, I would guess this script doesn't need your monitor to be on, but please clarify if my monitor should be on. Thanks!

**Comment by farshadz1997** [comment]
You don't need to leave your monitor on, just change the setting of sleep

**Comment by Ducky443747** [comment]
Ok, thanks.
