### ISSUE TITLE
Suspended account

### ISSUE THREAD

**Issue by Conirefle** [farshadz1997/Microsoft-Rewards-bot#418]
Yesterday i used the bot normally. today after 18 hours i took a flight and i moved near Pisa (from siciliy), btw always in italy.
All of my 6 account when i opend the bot got suspended simoltaniously, don't know the cuase if it's the bot or the region but do you have any clue on how to gain acess again? Or just create other account?

**Comment by RoromoriYuzu** [comment]
Yesterday, some of my accounts were also suspended.

**Comment by hidingfromu** [comment]
6 accounts suspended today

**Comment by zSavT** [comment]
Did you use headless mode?

**Comment by Conirefle** [comment]
> Did you use headless mode?

Never used the headless mode. I only use the  fast no image and session argument. Maybe the session was the problem with the change of position, idk.

**Comment by Karlweezer555** [comment]
got suspeneded today. 5 accounts all gone down the drain :(((((((((

**Comment by USForeignPolicy** [comment]
Suspended today.

Using bing-pong back in the 2016 days, I remember there being warnings that doing actions too quickly could cause bans.
So I would recommend against using --superfast.

That's how mine got suspended i think

Bing-pong would randomly choose a sleep time between each search, to make it look more organic.

**Comment by techhitnz** [comment]
As per https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/423, Microsoft are banning all accounts using the chrome driver.  Something like this needs to be implemented https://github.com/ultrafunkamsterdam/undetected-chromedriver

**Comment by USForeignPolicy** [comment]
> As per #423, Microsoft are banning all accounts using the chrome driver. Something like this needs to be implemented https://github.com/ultrafunkamsterdam/undetected-chromedriver

Ahh, great catch.

Hope it gets implemented. Shouldn't be too hard since the API seems mostly all the same.

**Comment by Conirefle** [comment]
do you guys have news? 2 days ago i created 6 new account and they got banned the day after. ps do you know  afast method to create new account?

**Comment by Rishabh4402** [comment]
is there any chance to get those accounts back?

**Comment by zSavT** [comment]
When Microsoft ban an account, they ban only rewards section or even the entire account?

**Comment by Conirefle** [comment]
> When Microsoft ban an account, they ban only rewards section or even the entire account?

Only the rewards part

**Comment by g2zer0** [comment]
the bot already uses undetected chromedriver.... you can see it in the import section at the beginning of the python script:

from selenium_stealth import stealth
import undetected_chromedriver as uc

**Comment by Hikaru4v** [comment]
> the bot already uses undetected chromedriver.... you can see it in the import section at the beginning of the python script:
> 
> from selenium_stealth import stealth
> import undetected_chromedriver as uc
> 

Saw this on another post today as well.

To OP - Please close this issue.
