### ISSUE TITLE
No web driver manager problem 

### ISSUE THREAD

**Issue by JittoJoseph** [farshadz1997/Microsoft-Rewards-bot#419]
![IMG-20230607-WA0000](https://github.com/farshadz1997/Microsoft-Rewards-bot/assets/78639807/b7d4921b-34d9-4f16-83e2-a5df99a01a79)

I have put --no-webdriver-manager 
But still getting the chromedriver not found error.
(Btw I don't want to use virtual-display as MSN shopping doesn't work with it for some reason)

**Comment by farshadz1997** [comment]
read here. https://github.com/farshadz1997/Microsoft-Rewards-bot/blob/master/setup.md#install-required-packages

**Comment by JittoJoseph** [comment]
Ok thanks
