### ISSUE TITLE
Accounts are banning in India 

### ISSUE THREAD

**Issue by iamdevprosun** [farshadz1997/Microsoft-Rewards-bot#423]
Please implement this - https://github.com/ultrafunkamsterdam/undetected-chromedriver
 As soon as possible into your script.. with normal chrome driver accounts are banning

**Comment by HIMANSHU7528** [comment]
seriously , not only in india everywhere the accounts are being banned by using detectable chrome driver ..I also want @farshadz1997 , bro to kindly include undetectable chrome driver in the bot . 🙏❤️

**Comment by gstreak** [comment]
new accounts are being banned as well!

**Comment by iamdevprosun** [comment]
They are now detecting the automation...so everytime you use farshad script with normal chrome driver your account will be banned.. so requesting farshad please implement this undetected chrome driver which will bypass Microsoft restriction..

**Comment by iamdevprosun** [comment]
@farshadz1997 please look into this matter!

**Comment by techhitnz** [comment]
Why is this closed?
