### ISSUE TITLE
Please we need this

### ISSUE THREAD

**Issue by beenruuu** [farshadz1997/Microsoft-Rewards-bot#426]
Please implement this - https://github.com/ultrafunkamsterdam/undetected-chromedriver
As soon as possible into your script.. with normal chrome driver accounts are banning, thanks!

**Comment by AG4lyf** [comment]
the script have something called [Selenium Stealty](https://pypi.org/project/selenium-stealth/)

**Comment by AG4lyf** [comment]
see [here](https://github.com/farshadz1997/Microsoft-Rewards-bot/blob/5aa6d6afe91fdd2aed6694bb8220ee2a671ccb94/ms_rewards_farmer.py#L186)
