### ISSUE TITLE
Mobile searches  loop

### ISSUE THREAD

**Issue by Thechosenwolf** [farshadz1997/Microsoft-Rewards-bot#43]
The bot loops opening and closing chrome indefinitely during mobile searches after reaching the mobile search bar. Searching manually on this screen breaks this loop and allows the bot to continue mobile searching automatically. 

The bot gets this far and then always closes and reopens without user intervention (image replicated without using bot):
![Capture1](https://user-images.githubusercontent.com/117106980/199064150-acd90041-a4df-4cc2-86fb-28096d866fe6.PNG)

Any ideas on fixes?

**Comment by farshadz1997** [comment]
run bot with --error and send it, it may help

**Comment by Thechosenwolf** [comment]
This came up:
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="bnp_bop_close_icon"]/img"}
  (Session info: chrome=107.0.5304.88)

**Comment by farshadz1997** [comment]
Thanks, I'll fix it.
