### ISSUE TITLE
Error using --browser flag

### ISSUE THREAD

**Issue by Culetto** [farshadz1997/Microsoft-Rewards-bot#432]
I get this error using "uc" as browser
![image](https://github.com/farshadz1997/Microsoft-Rewards-bot/assets/88935956/3033af78-40f4-4bec-85eb-6d40ee90b007)

**Comment by farshadz1997** [comment]
install requirements again

**Comment by Culetto** [comment]
> install requirements again

Ok i did that but now i got a new error 
![image](https://github.com/farshadz1997/Microsoft-Rewards-bot/assets/88935956/05f7f053-1548-44fa-a4a5-601082417f1b)
![image](https://github.com/farshadz1997/Microsoft-Rewards-bot/assets/88935956/b88c64ec-f276-4472-b92a-44f833915e39)

**Comment by farshadz1997** [comment]
will fix

**Comment by zSavT** [comment]
> > install requirements again
> 
> Ok i did that but now i got a new error ![image](https://user-images.githubusercontent.com/88935956/246167456-05f7f053-1548-44fa-a4a5-601082417f1b.png) ![image](https://user-images.githubusercontent.com/88935956/246167542-b88c64ec-f276-4472-b92a-44f833915e39.png)

same error
