### ISSUE TITLE
[Question] Is it less risky to use a headless virtual display than —headless command?

### ISSUE THREAD

**Issue by EM181-1** [farshadz1997/Microsoft-Rewards-bot#439]
Title

**Comment by Muddyblack** [comment]
Yes it is less risky. Virtual emulates a Display. Headless has just no display and this can be tracked.

**Comment by EM181-1** [comment]
> Yes it is less risky. Virtual emulates a Display. Headless has just no display and this can be tracked.

Alright thanks!
