### ISSUE TITLE
Script looping on "Ensuring login on Bing..."

### ISSUE THREAD

**Issue by Arturbrynow** [farshadz1997/Microsoft-Rewards-bot#44]
It just spits out:

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[ERROR] Time out raised.

And loops...

**Comment by farshadz1997** [comment]
try run without headless and add -error then check whether the issue remains.

**Comment by Arturbrynow** [comment]
It works without --headless but i need to use it because I dont have a display connected at all times

**Comment by Arturbrynow** [comment]
I checked it again without --headless, with a display connected and it just keeps looping on "[LOGIN] Ensuring login on Bing..."

**Comment by farshadz1997** [comment]
Does your problem is same as issue #45?

**Comment by Arturbrynow** [comment]
I'm sorry I was bothering you, because it started working again, with no issues and I didn't even do anything.
I do not understand how these kind of issues occur.

**Comment by farshadz1997** [comment]
There are so many variables which is out of my control such as regional pop ups in Bing, and they are unpredictable and debug them in headless mode make it even harder.
