### ISSUE TITLE
Infinite Loop on mobile search bing

### ISSUE THREAD

**Issue by Lucos18** [farshadz1997/Microsoft-Rewards-bot#45]
Hi, i would report a bug that affects mobile search that causes the page to load infinitely until Timeout.
The bug is caused by the pop up shown in photo, that disables for what ever reason the button to see if we are logged in bing
![popup-blocking](https://user-images.githubusercontent.com/58827838/199836279-2e445a81-db59-42ff-b6f8-ae0200596106.PNG)
The popup will not show everytime when we do a mobile searches quest, and one fix to this problem can be a click to the ok button on the popup, closing the new page that it opens, go back to the original page and refresh, and the popup will disappear.
Or simply reduce the timeout timer from 300 to 60 and pray that the popup will not appear the next time you do the mobile searches

**Comment by farshadz1997** [comment]
Hi,
This can be easily fixed by replacing Chrome user agent with Edge user agent for mobile, I'll update it in few hours.
