### ISSUE TITLE
Detected

### ISSUE THREAD

**Issue by Permissiblekillos** [farshadz1997/Microsoft-Rewards-bot#48]
3 accounts banned after using for about a week

**Comment by Permissiblekillos** [comment]
i mean temp btw but only used 6 in total

**Comment by farshadz1997** [comment]
There is always a small risk of being detected, I tried to make the bot's browser variables look like a normal browser to reduce the chance of being detected.
They can also detect you from your IP address by monitoring your traffic to their servers.

**Comment by Permissiblekillos** [comment]
know any type of solutions?

**Comment by farshadz1997** [comment]
there's no concern if your account gets locked, try to change IP and don't use outlook.

**Comment by yoyodolo** [comment]
need more details
were you using in headless mode? or something?
