### ISSUE TITLE
Add GOALS to the bot and send it to Telegram when the account is in the necessary points to redeem.

### ISSUE THREAD

**Issue by beenruuu** [farshadz1997/Microsoft-Rewards-bot#51]
Hello, if you could add that you can alert via telegram when you reach your microsoft goal for example: Amazon and assign the goal it would be great, and it's very comfortable. I like to redeem manually but I don't always know when it's my turn to redeem between so many accounts. Thanks for your magnific job!!

**Comment by farshadz1997** [comment]
Hello,
I'm a bit busy now but I'll add it later.

**Comment by farshadz1997** [comment]
Added to bot, get the latest update.
