### ISSUE TITLE
Add daily videos and article and blogs features

### ISSUE THREAD

**Issue by TatsP** [farshadz1997/Microsoft-Rewards-bot#52]
The bot can earn around 100-150 points daily by watching short videos as well as reading articles on MSN and Bing website, Please add these two features as it will result in significant points gain, here are the articles providing more information regarding the same. 
https://www.reddit.com/r/MicrosoftRewards/comments/wn1and/msn_fitness_hyper_optimization_i_aint_got_time_to/
https://reddit.com/r/MicrosoftRewards/comments/vscyfu/us_found_new_daily_points/
https://www.reddit.com/r/MicrosoftRewards/comments/n50k0h/all_living_sticky_3_please_check_here_for_updates/

**Comment by farshadz1997** [comment]
Thanks, I didn't know that. I'll work on it.

**Comment by TatsP** [comment]
> Thanks, I didn't know that. I'll work on it.

Welcome, also if possible add the feature to complete the new account quiz as well as the feature to click on banners such as "Here's 100 points for joining" or other such offers, they provide a lot of points.

**Comment by Prabh-Saini** [comment]
Well since MSN Articles cannot be implemented as it only works on the MS Edge mobile app, and MSN Fitness is the main topic of #166, and progress has been made there. I think it is time to close this issue. @farshadz1997.
