### ISSUE TITLE
Feature request : auto update

### ISSUE THREAD

**Issue by Gnaagounet** [farshadz1997/Microsoft-Rewards-bot#54]
Hello,

First, thank you for this work. 

It should be interesting to add an auto update of the py script everyday before launch.

**Comment by farshadz1997** [comment]
Hello, 
you're welcome
I need do some research about it and it may take while.

**Comment by Prabh-Saini** [comment]
> While this sounds like a good idea - some of us manually edit the file each time we update it to allow the use of Authenticator. This would cause me to have to double check it daily to make sure it hasn't overwritten my edits and then run it. If there was a flag for Authenticator that would skip the password prompt then it might be workable. That is just my input and I appreciate the work you are doing.

my solution is that a warning will pop up in terminal and discord/telegram that you are running an outdated version, and to update run `py ms_rewards_farmer.py --update`. the bot will know when it is outdated using a .txt file which just states the version something along the lines of 160323a (16/03/23; a = first update on this day). when the bot runs it will check if there has been any updates and it will then send the messages.
