### ISSUE TITLE
Where can you buy phone numbers for redeeming rewards?

### ISSUE THREAD

**Issue by CTAK-CO6AK** [farshadz1997/Microsoft-Rewards-bot#55]
Any working websites?

**Comment by arcadiaplanitia** [comment]
textverified.com seems to be mostly consistent

**Comment by CTAK-CO6AK** [comment]
Will it work if I use an US number on the UK account?

**Comment by arcadiaplanitia** [comment]
not sure about that, i only use US accounts

**Comment by CTAK-CO6AK** [comment]
> not sure about that, i only use US accounts

What's your accounts ban rate?
I have managed to reedeem rewards on 2 accounts: UK and US
All my other accounts (10+) got banned
I've been using proxies and gmail accounts

**Comment by CTAK-CO6AK** [comment]
Well for US accounts you can use textverified.com
Or 5sim.biz - USA provider virtual32
