### ISSUE TITLE
Use simple math to indicate how many of my goal I could buy through telegram

### ISSUE THREAD

**Issue by leem919** [farshadz1997/Microsoft-Rewards-bot#56]
When you have enough points to purchase your goal in telegram, I think it should also tell you how many of said goal you can buy because my account has a lot of points and it will always tell me that I can buy my goal.

**Comment by farshadz1997** [comment]
Just to make it clear, for example you have 40k points in your account and it says you can redeem 3 * $10 Amazon gift card with your points.
Am I right?
