### ISSUE TITLE
Run 24h/7?

### ISSUE THREAD

**Issue by xCorteX** [farshadz1997/Microsoft-Rewards-bot#6]
is there a possibility that it starts automatically every 24 hours?

**Comment by kobi-wan** [comment]
Under Windows I am using Task Scheduler for this. You also have to slightly modify the script, so that it does not ask for running at a specific time.

**Comment by xCorteX** [comment]
could you tell me how to remove the time requirement?

**Comment by kobi-wan** [comment]
An easy way is to just replace the `answer = input(...` in row 1048 with `answer = 'n'`
Also delete (or comment out with #) the `input(...` in line 1068.

**Comment by xCorteX** [comment]
ty  :)

**Comment by kobi-wan** [comment]
What does it say? Is there an error-message? Maybe you made a mistake when you edited it.

**Comment by xCorteX** [comment]
script funktioniert einwandfrei, nur beim task scheduler ploppt er auf und verschwindet wider

**Comment by xCorteX** [comment]
script works fine, only the task scheduler pops up and disappears again

**Comment by kobi-wan** [comment]
How is it started in Task Scheduler?

**Comment by xCorteX** [comment]
it is set to start every day, but if I run it manually in the task scheduler, the script starts for 1sec, you can also see the logo in the script and then the window closes.  I can take some pictures for you after work today of how it's set up.  and thanks for your help

**Comment by kobi-wan** [comment]
Did you set Start in path? You could re-insert the last input (row 1068) in order to leave the script window open. So you can see what the problem is.

**Comment by xCorteX** [comment]
I found the error, the log file is saved in system32 if you start it via task scheduler and my accounts were already done.  now it works fine

**Comment by farshadz1997** [comment]
Hi,
I will add this feature in next few weeks.
