### ISSUE TITLE
All account is getting locked

### ISSUE THREAD

**Issue by Rickyose** [farshadz1997/Microsoft-Rewards-bot#61]
Hi i want to ask why many account can getting locked ?? i mean i run only 1 acc per pc. maybe because the bot dont save cookies ? since i got many info that the acc being abused, i think microsoft think i login from many different device everytime i run the bot, thats why its getting locked ?? can you please fix this issue dev , thank you.

**Comment by Rickyose** [comment]
from my experience its sometime when i browsing on native browser, its going alright but when its on bot its locked, thats why i think its about cookies

**Comment by farshadz1997** [comment]
Hi,
as they said in TOS each household can use 6 accounts per PC.
Maybe related to cookie and session, unfortunately we don't know how Microsoft system works and how it processes our data to decide what to do with our accounts.

**Comment by Rickyose** [comment]
thanks for the reply, no i am not use 6 acc, i am only use 1 acc. so you dont save cookies because microsoft might use the data to confirm that we use bot ??? btw can you give key trigger to pause bot while still keep the browser still open ? so we can unlock the acc on bot browser. i try to ctrl+c and the bot said its paused, but its close the browser so i cant unlock the acc from bot browser

**Comment by farshadz1997** [comment]
No, I use cookie and session, add `--session` when you want to start the bot to save cookies in session and I never get locked.
The feature you requested is currently out of my skill.
