### ISSUE TITLE
Error: Unrecognized argument (Telegram)

### ISSUE THREAD

**Issue by Rickyose** [farshadz1997/Microsoft-Rewards-bot#62]
Hello, sorry to create another question in short time, but somehow i cant use telegram argument, so here is my argument that i use

--session --telegram 5XXXXXXX76:AAHvXXXXXXXXXX2USNydauaG247a8okMz24 8XXXXX590

**Comment by guilloutran** [comment]
I agree. It doesn't seem to work

**Comment by Rickyose** [comment]
> I agree. It doesn't seem to work

Lol just found the root problem, its because i dont upgrade my bot, you might want to try it (if not fix the issue you might need to pip install -r requirements.txt once more)
