### ISSUE TITLE
Telegram Enhancement 

### ISSUE THREAD

**Issue by guilloutran** [farshadz1997/Microsoft-Rewards-bot#64]
So I think it would be wise to suggest point to money conversion in Telegram to give a sense of how much money does the bot earn or how much does the point worth?

In Europe, 7500 = 5€ or 1500 = 1€ 
In United States, it's different

So could you add the function of convert the point to euro in Telegram messages by adding a simple covert code in python?

**Comment by farshadz1997** [comment]
wouldn't this make the report messy? plus that I don't know any way to recognize user's country to convert points to desired currency.
