### ISSUE TITLE
multi accounts - best practices

### ISSUE THREAD

**Issue by Gnaagounet** [farshadz1997/Microsoft-Rewards-bot#66]
Hello,

I use this script since 1 month (with 2 accounts at first, then 4) and it works greats, thank you @farshadz1997 for your work.

I would like to know how people use it with more accounts, how they split them with multiple IPs, VPN, phone number, etc...

What are the best practices to farm with more accounts ?

**Comment by farshadz1997** [comment]
Hello,

It's my pleasure.
My opinion is don't use same IP for more than six accounts, make sure your accounts don't get unusual activity by logging in from different IP locations, plus that don't use same number multiple times for redeem in short term.

**Comment by Gnaagounet** [comment]
Thanks for your return. My question is also about best practices for technically using multiple accounts:
- VPS (one per batch of 4-6 accounts).
- Several virtual machines (one per 4-6 accounts with a VPN settings).
- A virtual machine (with several VPN config if it is technically possible with 4-6 accounts for each configuration ?)

**Comment by farshadz1997** [comment]
I think you can work with a virtual machine with several VPN config for each group of your accounts.

**Comment by lonsdalien** [comment]
Does Microsoft detect common commercial VPN IPs?

**Comment by farshadz1997** [comment]
I don't think so, I use Express VPN, Nord VPN

**Comment by lonsdalien** [comment]
ok perfect, thanks

**Comment by Gnaagounet** [comment]
Thank you @farshadz1997 for your reply

**Comment by farshadz1997** [comment]
don't mention it

**Comment by Rickyose** [comment]
is there any advise how to register email for microsoft rewards ? how many days for delay to create between account ?? in my case i register 1 acc each day till got 4 acc but getting banned all but one

**Comment by zuko726** [comment]
> Don't use same names, don't use same IP when you are creating account, don't use Outlook and don't set your accounts as backup account of each other

if not outlook then what should we use?

**Comment by farshadz1997** [comment]
Any other services like Gmail and Proton Mail and etc.
