### ISSUE TITLE
(Adding Argument) Turn to manual

### ISSUE THREAD

**Issue by Rickyose** [farshadz1997/Microsoft-Rewards-bot#71]
Hi thank you for your always update bot, its really good for many of us, i just want to make suggestion, it might be good to add argument that if used will open the browser and doing nothing, this will be helpful if owner want to do manual thing in his account such as but not limited:

1. redeem rewards
2. want to unlock their ms.rewards account

i think its will be good feature since it will be more safe to do anything regarding ms reward account on its bot itself, if we use native browser it might trigger bot flag, since we will use other browser that not we usually used

**Comment by farshadz1997** [comment]
Hi,
it makes sense, I'll add it soon.
