### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by HQModz** [farshadz1997/Microsoft-Rewards-bot#74]
Hello, can you possibly add timestamps (including the date) that shows when the bot has completed? Thank you!

**Comment by Rickyose** [comment]
> Hello, can you possibly add timestamps (including the date) that shows when the bot has completed? Thank you!

isnt when you use telegram argument you will now when the bot is completed by seeing time the chat bot being sended ??

**Comment by HQModz** [comment]
A simple timestamp when an account completes would be very useful. I'd greatly appreciate if you could add it, I'd rather not use Telegram just for this and I think it makes sense to have it in the bot log. 

![Screenshot_17](https://user-images.githubusercontent.com/51813680/212573398-5873e958-6ee4-4ed9-b990-b153bd15c2dd.jpg)

**Comment by farshadz1997** [comment]
Ok, I'll add it
