### ISSUE TITLE
Automatically run the program without pressing enter

### ISSUE THREAD

**Issue by inverspe** [farshadz1997/Microsoft-Rewards-bot#76]
Add an option to make it automatic so you don't have to press enter every time it will start on point once you run the script

**Comment by Rickyose** [comment]
Yes i think this a good feature too, i think 5-10 second before script running is enough for someone who really want to see their script status. i already add it at my custom script, but it would be great if this become feature here

**Comment by C63H88CoN14O14P** [comment]
I also very much support this proposal, so that I can let the windows task scheduler to execute regularly, in order to achieve a high degree of automation.
And many thanks to the authors for their efforts.

**Comment by Gnaagounet** [comment]
If you use Ubuntu server to farm, you can use command to script the Enter input :

echo -ne '\n' | python3 ms_rewards_farmer.py

**Comment by C63H88CoN14O14P** [comment]
> 

I found that you can do what you need with a vbs script
##### The code is as follows
Dim Shell
Set Shell=WScript.CreateObject("WScript.Shell")
Shell.Run "D:\Desktop\Microsoft-Rewards-bot-master\ms_rewards_farmer.py"
WScript.Sleep 7000 #delay 7000ms
Shell.SendKeys "{ENTER}"
#######
Just save it as a .vbs
Don't forget to change your path!
