### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by SuperKaa** [farshadz1997/Microsoft-Rewards-bot#79]
hi, when i run this i have 4 accounts and after it finishes 1 account then it starts retrying it it doenst move onto the next

**Comment by farshadz1997** [comment]
Hi,
don't you get any error? maybe it didn't finish your account.

**Comment by SuperKaa** [comment]
hi, i dont get any error once it finishes my account it retrys for no reason and then gets stuck on the logging into bing

**Comment by SuperKaa** [comment]
![image](https://user-images.githubusercontent.com/106885631/214681564-289d9da3-7bea-4f4c-89e1-59646827dc35.png)

look its been stuck like this for a while

**Comment by farshadz1997** [comment]
The second time it open browser as a mobile device to do Bing search, but it seems like that your browser runs same as windows so the code for mobile which it's trying to execute could not complete properly.
Have you changed mobile user agent or add one in accounts?

**Comment by SuperKaa** [comment]
No I have t added any mobile user agents I also tried reinstalling this still it did not work

**Comment by farshadz1997** [comment]
Ok, can you send me the html source of Bing page (Mobile) through GitHub gist?
This is the first time that I see mobile page like this.

**Comment by SuperKaa** [comment]
https://gist.github.com/SuperKaa/83383f1264c53e9f7577b1b6a8981540#file-gistfile1-txt

**Comment by SuperKaa** [comment]
my problem is fixed now i downloaded the new version of this and it worked thanks

**Comment by SuperKaa** [comment]
i definitely recommend adding proxy switch for each account it does 😀

**Comment by farshadz1997** [comment]
> i definitely recommend adding proxy switch for each account it does 😀

Currently I'm a bit busy but I'll add it in future.
