### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mccrena** [farshadz1997/Microsoft-Rewards-bot#80]
python ms_rewards_farmer.py
  File "ms_rewards_farmer.py", line 47
    def browserSetup(isMobile: bool, user_agent: str = PC_USER_AGENT) -> WebDriver:
                             ^
SyntaxError: invalid syntax

no arguments
Debian 5.10.162-1

**Comment by farshadz1997** [comment]
I think this error comes from you not script, maybe you changed the script accidentally. Try to download it again.

**Comment by mccrena** [comment]
I tried it again , start from scratch, but it still exists, I will try it on Windows 11.

**Comment by farshadz1997** [comment]
If there's a syntax error in script then it would be happen for all not just you, something else stopped you from running it.

**Comment by mccrena** [comment]
yeah there are something wrong with my linux, it works well on my windows 11

**Comment by farshadz1997** [comment]
shall I close issue?

**Comment by mccrena** [comment]
yes
