### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by qingzt** [farshadz1997/Microsoft-Rewards-bot#81]
Every time the program runs here it will restart. I don't know how to fix it. please help me
![image](https://user-images.githubusercontent.com/116171689/215265688-24d3bfbc-14ef-4255-98a4-818ce53a4e66.png)

**Comment by farshadz1997** [comment]
You can't get words from either google trends or backup API, try to change your IP or use DNS, maybe these services blocked in your region.

**Comment by qingzt** [comment]
Thanks for your help.
I used a proxy which caused an error with urllib3, now I have found a solution
[https://github.com/pypa/pip/issues/9216#issuecomment-741836058](url)

**Comment by farshadz1997** [comment]
you're welcome.

**Comment by yukiryo** [comment]
> 

What is the solution, I have the same issue

**Comment by Rickyose** [comment]
Bump this issue
