### ISSUE TITLE
or add your argument like --fast or --session

### ISSUE THREAD

**Issue by copsstar** [farshadz1997/Microsoft-Rewards-bot#84]
or add your argument like --fast or --session

thx

**Comment by farshadz1997** [comment]
what?!

**Comment by copsstar** [comment]
I did not understand or and how I have to add optinal arguments because I would like the script to make several accounts at the same time and that is faster but also that it is activated automatically on my pc (sorry is google traduction)

**Comment by farshadz1997** [comment]
You can't farm accounts parallel.
if you want to use arguments, open terminal in farmer directory and type command like this:
```python ms_rewards_farmer.py --session --fast```

**Comment by copsstar** [comment]
OK THX
