### ISSUE TITLE
Feature Request: MSN Shopping Game Automation

### ISSUE THREAD

**Issue by VentusWK** [farshadz1997/Microsoft-Rewards-bot#85]
Hello,

In the [shopping section of MSN](https://www.msn.com/en-us/shopping), there is a section called "Shopping Games" (visualized below) where you can earn up to 100 reward points every day just by answering which of the products has the lowest price. If you go to the website yourself, you might need to scroll down quite a bit before you find it.

![image](https://user-images.githubusercontent.com/29739395/215357388-fb5fade7-f9c5-4efd-83a8-88fc2354904a.png)

These are points often ignored by many scripts, so I was wondering how practical it could be to automate this process for more points.

In [an r/MicrosoftRewards Reddit thread](https://www.reddit.com/r/MicrosoftRewards/comments/10dpg01/msn_shopping_game_script/), a user had written some JavaScript to make this game easier/faster. The code limits the number of cards shown to 1, which defaults to the correct answer. By executing [this JavaScript](https://pastebin.com/Vrxpbh65) through a bookmark, the game becomes trivial. I also have the "URL" for the bookmark below if you wanted to try it for yourself.

```
javascript: (() => {var msnShoppingGamePane = document.querySelector("shopping-page-base")?.shadowRoot.querySelector("shopping-homepage")?.shadowRoot.querySelector("msft-feed-layout")?.shadowRoot.querySelector("msn-shopping-game-pane"); if(msnShoppingGamePane != null){msnShoppingGamePane.cardsPerGame = 1;msnShoppingGamePane.resetGame();}else alert("Unable to locate the shopping game!");})();
```

Thanks for working on this project, and I hope this helps!

**Comment by farshadz1997** [comment]
Hello,
Thanks for the script, I'll try to add it.

**Comment by W5x** [comment]
@farshadz1997 , please also add this on the GUI version , thanks in advance.

**Comment by handaishaan10** [comment]
not working'

**Comment by jcdfs** [comment]
They did an update. It's not working anymore.
