### ISSUE TITLE
Mobile Search Not Working

### ISSUE THREAD

**Issue by pro7777777777** [farshadz1997/Microsoft-Rewards-bot#87]
Hi the program keeps getting stuck after the desktop searches. It finishes the desktop searches then logs back in and it times out. Can anyone help?

**Comment by farshadz1997** [comment]
Hi, 
is your problem same as #83?

**Comment by pro7777777777** [comment]
Yes, I tried the solution there but it did not work.

**Comment by farshadz1997** [comment]
I'm working on it

**Comment by pro7777777777** [comment]
Ok Thanks in advance 

Hope you get through

**Comment by pro7777777777** [comment]
Hi I was wondering if you could use something like an emulator to fix the mobile searches similar the ABS X
https://github.com/apersongithub/ABS-X

**Comment by farshadz1997** [comment]
@pro7777777777 can you please try this to see whether it works for you or not.
[ms_rewards_farmer.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot/files/10689783/ms_rewards_farmer.zip)

**Comment by farshadz1997** [comment]
@pro7777777777 if you added mobile user agent in your accounts, remove it, this will fix your problem
