### ISSUE TITLE
--account-browser Not open browser

### ISSUE THREAD

**Issue by Rickyose** [farshadz1997/Microsoft-Rewards-bot#88]
Hi i want to report a bug when using argument --account-browser , when i use the argument its open browser 1 second then the bot auto close the browser

and if i can ask , can the argument read the account.json instead need to add ACCOUNT in --account-browser ACCOUNT argument ?? i mean  i think people use one account in one folder bot, so i wonder if reading from account.json is more easier to use than to add ACCOUNT manually.

thank you

**Comment by farshadz1997** [comment]
> Hi i want to report a bug when using argument --account-browser , when i use the argument its open browser 1 second then the bot auto close the browser

Hi, as long as you don't press enter in terminal Browser won't close unless you have webdriver issue.

> and if i can ask , can the argument read the account.json instead need to add ACCOUNT in --account-browser ACCOUNT argument ?? i mean i think people use one account in one folder bot, so i wonder if reading from account.json is more easier to use than to add ACCOUNT manually.

I didn't do that because if there's no session exist for account displaying it and choose it would be useless, so it gets account from arg and check if session exists then it opens otherwise sends back an error to say there's no session exists for the account.

**Comment by Rickyose** [comment]
> > Hi i want to report a bug when using argument --account-browser , when i use the argument its open browser 1 second then the bot auto close the browser
> 
> Hi, as long as you don't press enter in terminal Browser won't close unless you have webdriver issue.
> 
> > and if i can ask , can the argument read the account.json instead need to add ACCOUNT in --account-browser ACCOUNT argument ?? i mean i think people use one account in one folder bot, so i wonder if reading from account.json is more easier to use than to add ACCOUNT manually.
> 

hi, thanks for the reply

so i try to use --account-browser ACCOUNT arguments account on multiple account, and seems its have same result, i dont think its because webdriver issue because if i dont use --account-browser  the bot working as usual. 

The format i use was: 

--session --account-browser xxx@xxx.com
and
--account-browser xxx@xxx.com
both have same result

> I didn't do that because if there's no session exist for account displaying it and choose it would be useless, so it gets account from arg and check if session exists then it opens otherwise sends back an error to say there's no session exists for the account.

its just my opinion but if there is no session/profile exist on the account then i think people dont use the --account-browser in the first place? it might be there is misunderstanding, i mean we still need to use --account-browser argument but we dont need to add ACCOUNT manually, the bot is read it from config.json. sorry i dont mean to push you too much but i try to mass use the bot, 1 account 1 folder bot. and i think to need to add custom string to use --account-browser in every acc is rather difficult if we try to scale it up

**Comment by farshadz1997** [comment]
> so i try to use --account-browser ACCOUNT arguments account on multiple account, and seems its have same result, i dont think its because webdriver issue because if i dont use --account-browser the bot working as usual.
> 
> The format i use was:
> 
> --session --account-browser [xxx@xxx.com](mailto:xxx@xxx.com) and --account-browser [xxx@xxx.com](mailto:xxx@xxx.com) both have same result

No it opens different session not same, for example if you open account.microsoft.com you see your account already signed in that you have opened. when you use ```--account-browser``` program won't consider all other args and it just opens session for the account.



> its just my opinion but if there is no session/profile exist on the account then i think people dont use the --account-browser in the first place? it might be there is misunderstanding, i mean we still need to use --account-browser argument but we dont need to add ACCOUNT manually, the bot is read it from config.json. sorry i dont mean to push you but if we try to mass use the bot, 1 account 1 folder bot. and need to add custom string to use --account-browser in every acc, I think it will be rather difficult if we try to scale it up

I think you didn't understand the main function of ```--account-browser``` I added it due to request of another user that he wanted to use the session for manual use such as (unlocking account, changing password, redeeming) and not to login to account in another browser. if you want to use sessions just pass ```--session``` then bot creates session for all of them from ```accounts.json```

**Comment by Rickyose** [comment]
> 
> No it opens different session not same, for example if you open account.microsoft.com you see your account already signed in that you have opened. when you use `--account-browser` program won't consider all other args and it just opens session for the account.
> 

sorry seems i am a bit confused, so do this format is correct??

ms_rewards_farmer.py --account-browser xxx@xxx.com

 if its wrong cant you give the correct example to use the argument?

**Comment by farshadz1997** [comment]
that's right

**Comment by farshadz1997** [comment]
can I close issue if your problem fixed?

**Comment by Rickyose** [comment]
> can I close issue if your problem fixed?

the problem still persist but i doing some modification on bot so it can work like i wanted, but sure you can close this
