### ISSUE TITLE
Speed up the program

### ISSUE THREAD

**Issue by Andr1x66** [farshadz1997/Microsoft-Rewards-bot#9]
Is there a way to speed up every single process of the program to make it faster? Ty

**Comment by Josexv1** [comment]
Remember faster actions lead to ban, because it's bot like behaviour.

**Comment by aydynx** [comment]
> I set high delays for slow connection so they can use it with out problem. I will think of a way to add an option to increase speed

why need for sleep? just check URL of tab and/or waitUntilVisible/waitUntilClickable

**Comment by Josexv1** [comment]
> why need for sleep? just check URL of tab and/or waitUntilVisible/waitUntilClickable

This comment would be good as a new Feature issue.

**Comment by farshadz1997** [comment]
> why need for sleep? just check URL of tab and/or waitUntilVisible/waitUntilClickable

Then if you have fast internet connection, bot clicks on the button at the moment it appears or visible and this not very human so sleep is required.
