### ISSUE TITLE
UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value

### ISSUE THREAD

**Issue by MawrthMorse** [farshadz1997/Microsoft-Rewards-bot#92]
how to fix this issue?

**Comment by MawrthMorse** [comment]
> C:\Users\Joshua>python D:\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py --discord https://discord.com/api/webhooks/1072873246418018326/SSVscha34365oSlxsHOdcIBphmRYDcl_ePyOlbCXR7M4ecyuxFUEMSZBvtlPmml1woVf --session --edge
> 
>     ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
>     ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
>     ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
>     ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
>     ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
>     ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
>             by @Charlesbel upgraded by @Farshadz1997        version 2.1
> 
> [INFO] everyday: False
> [INFO] headless: False
> [INFO] session: True
> [INFO] error: False
> [INFO] fast: False
> [INFO] telegram: None
> [INFO] discord: ['https://discord.com/api/webhooks/1072873246418018326/SSVscha34365oSlxsHOdcIBphmRYDcl_ePyOlbCXR7M4ecyuxFUEMSZBvtlPmml1woVf']
> [INFO] edge: True
> [INFO] shutdown: None
> [INFO] account_browser: None
> [INFO] start_at: None
> 
> [LOGS] Logs loaded successfully.
> 
> ********************Your Email********************
> 
> 
> Traceback (most recent call last):
>   File "C:\Users\Joshua\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
>     self.process = subprocess.Popen(cmd, env=self.env,
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Joshua\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\Joshua\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1471, in farmer
>     browser = browserSetup(False, PC_USER_AGENT)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 86, in browserSetup
>     browser = webdriver.Edge(options=options)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Joshua\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\edge\webdriver.py", line 61, in __init__
>     super().__init__(DesiredCapabilities.EDGE['browserName'], "ms",
>   File "C:\Users\Joshua\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
>     self.service.start()
>   File "C:\Users\Joshua\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
>     raise WebDriverException(
> selenium.common.exceptions.WebDriverException: Message: 'msedgedriver' executable needs to be in PATH. Please download from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1602, in <module>
>     main()
>   File "D:\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1588, in main
>     farmer()
>   File "D:\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1548, in farmer
>     browser.quit()
>     ^^^^^^^
> UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value

**Comment by farshadz1997** [comment]
Where did you save edge/chrome webdriver? Try both c:/windows and bot directory

**Comment by gasu95** [comment]
Hi! I have the same problem, I tried to save it in both places and still doesn't work, what can I do now?
