### ISSUE TITLE
your email

### ISSUE THREAD

**Issue by MawrthMorse** [farshadz1997/Microsoft-Rewards-bot#93]
It says that logged in but it typed your email.

> Microsoft Windows [Version 10.0.19045.2546]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Joshua>python D:\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py --everyday --discord https://discord.com/api/webhooks/1072873246418018326/SSVscha34365oSlxsHOdcIBphmRYDcl_ePyOlbCXR7M4ecyuxFUEMSZBvtlPmml1woVf --session --error

    ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
            by @Charlesbel upgraded by @Farshadz1997        version 2.1

[INFO] everyday: True
[INFO] headless: False
[INFO] session: True
[INFO] error: True
[INFO] fast: False
[INFO] telegram: None
[INFO] discord: ['https://discord.com/api/webhooks/1072873246418018326/SSVscha34365oSlxsHOdcIBphmRYDcl_ePyOlbCXR7M4ecyuxFUEMSZBvtlPmml1woVf']
[INFO] edge: False
[INFO] shutdown: None
[INFO] account_browser: None
[INFO] start_at: None

[INFO] Starting everyday at 09:20.

[INFO] Farmer will start at 09:20

[LOGS] Logs loaded successfully.

********************Your Email********************

DevTools listening on ws://127.0.0.1:60781/devtools/browser/75e0c695-18e9-4205-b0bf-8e398c6cabac
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...

**Comment by MawrthMorse** [comment]
![image](https://user-images.githubusercontent.com/107622133/217742039-854b1c78-ec37-41b1-93a2-908ba7c3560f.png)

**Comment by farshadz1997** [comment]
You need to emter your credentials in accounts.json, this is just sample, read the readme

**Comment by MawrthMorse** [comment]
![12](https://user-images.githubusercontent.com/107622133/217817295-86ed6630-0ae6-43c8-b502-a4ddd0861f48.png)
its this wrong?

**Comment by farshadz1997** [comment]
That's right, just remove mobile user agent as you don't know how to use it, this can cause serious error if you don't put right user agent

**Comment by MawrthMorse** [comment]
I remove the mobile user agent and run it again and it still typed your email

**Comment by MawrthMorse** [comment]
ohhhhhh i didn't save it bruhh😭😭😭 so stupid, thanks for the help!
