### ISSUE TITLE
[MSN GAME] Failed to complete MSN shopping game !

### ISSUE THREAD

**Issue by laoka3** [farshadz1997/Microsoft-Rewards-bot#94]
Any idea how to solve this problem?

**Comment by farshadz1997** [comment]
There must be an error when tried to complete it such as, missing card, network timeout or any others, unfortunately this quiz highly depends on internet connection

**Comment by inverspe** [comment]
its not available in all countries

**Comment by laoka3** [comment]
Hey guys, FYI, I noticed that if I maximize the browser (window) it will work out perfectly. If not fullscreen then it will fail.
